FREEDICTDIR ?= ..
DISTFILES = COPYING eng-ara-nophon.tei Makefile README ChangeLog
include $(FREEDICTDIR)/tools/Makefile.common
UNSUPPORTED_PLATFORMS = evolutionary

clean::
	rm -f ara-eng.c5 ara-eng.c5.index ara-eng.c5.dict
	rm -f eng-ara.c5 eng-ara.c5.index eng-ara.c5.dict
	rm -f *.dz *.bz2 eng-ara.tei

