FREEDICTDIR ?= ..
DISTFILES = AUTHORS COPYING swa-eng.tei freedict-dictionary.css freedict_swa-eng.dtd freedict_swa-eng.rng freedict_swa-eng.xml Makefile README ChangeLog
include $(FREEDICTDIR)/tools/Makefile.common
