FREEDICTDIR ?= ../../
DISTFILES = AUTHORS COPYING swh-eng.tei freedict-dictionary.css freedict-P5.dtd \
            freedict-P5.rng freedict-P5.xml Makefile README ChangeLog INSTALL
include $(FREEDICTDIR)/tools/Makefile.common
