FREEDICTDIR ?= ../../
DISTFILES = AUTHORS ChangeLog COPYING nld-fra.tei INSTALL Makefile NEWS README \
     freedict-P5.dtd freedict-P5.rng freedict-P5.xml freedict-dictionary.css
supported_phonetics=
include $(FREEDICTDIR)/tools/Makefile.common
#include $(toolsdir)/ergane/Makefile.inc


