FREEDICTDIR ?= ..
DISTFILES = eng-por.tei Makefile COPYING INSTALL NEWS README ChangeLog
# Clear this variable, because currently the .tei file already contains
# phonetics information.
supported_phonetics =
include $(FREEDICTDIR)/tools/Makefile.common

