FREEDICTDIR ?= ../../
DISTFILES = AUTHORS ChangeLog COPYING eng-srp.tei Makefile NEWS README \
INSTALL freedict-P5.dtd freedict-P5.rng freedict-P5.xml freedict-dictionary.css
# Clear this variable, because currently the .tei file already contains
# phonetics information.
supported_phonetics =
include $(FREEDICTDIR)/tools/Makefile.common
UNSUPPORTED_PLATFORMS = evolutionary
