FREEDICTDIR ?= ../../
DISTFILES = AUTHORS ChangeLog COPYING INSTALL Makefile NEWS README deu-swe.tei \
 freedict-P5.dtd freedict-P5.rng freedict-P5.xml freedict-dictionary.css
supported_phonetics=
include $(FREEDICTDIR)/tools/Makefile.common

