FREEDICTDIR ?= ../../
DISTFILES = AUTHORS ChangeLog COPYING mkd-bul.tei INSTALL Makefile NEWS README \
    freedict-P5.dtd freedict-P5.rng freedict-P5.xml freedict-dictionary.css
supported_phonetics=

include $(FREEDICTDIR)/tools/Makefile.common
