FREEDICTDIR ?= ../../
DISTFILES = AUTHORS COPYING swh-pol.tei freedict-dictionary.css freedict-P5.dtd \
            freedict-P5.rng freedict-P5.xml Makefile README ChangeLog INSTALL bible-names.tsv
include $(FREEDICTDIR)/tools/Makefile.common
