FREEDICTDIR ?= ..
DISTFILES = AUTHORS COPYING ChangeLog INSTALL Makefile \
	README lg1-lg2.tei freedict-P5.rng freedict-P5.xml \
	freedict-dictionary.css freedict-P5.dtd
include $(FREEDICTDIR)/tools/Makefile.common
