FREEDICTDIR ?= ../../
DISTFILES = san-deu.tei Makefile ChangeLog COPYING \
INSTALL freedict-P5.dtd freedict-P5.rng freedict-P5.xml freedict-dictionary.css
UNSUPPORTED_PLATFORMS = evolutionary

# XXX actually, this switch is not reqd for reverse indexing
TEI2DICTFLAGS = -a 

include $(FREEDICTDIR)/tools/Makefile.common
