FREEDICTDIR ?= ..
DISTFILES = san-deu.tei Makefile
UNSUPPORTED_PLATFORMS = evolutionary

# XXX actually, this switch is not reqd for reverse indexing
TEI2DICTFLAGS = -a 

include $(FREEDICTDIR)/tools/Makefile.common
