FREEDICTDIR ?= ..
DISTFILES = fra-bre.tei geriadur.dtd tei.css COPYING README tei.xsl Makefile \ \
			freedict-P5.rng freedict-P5.dtd
supported_phonetics=
include $(FREEDICTDIR)/tools/Makefile.common
