# The line below is really just a fallback and only works if you have got a copy of the tools directory at this location. It's better to set the environment variable in your shell.
FREEDICT_TOOLS ?= ../../tools
DISTFILES = ChangeLog eng-tur.tei eng-tur.tei.header README ChangeLog ingtur-ing.utf8 \
	    ingtur-tur.utf8 eng-tur2tei.pl general.footer Makefile  \
      INSTALL freedict-P5.dtd freedict-P5.rng freedict-P5.xml freedict-dictionary.css
supported_phonetics=
include $(FREEDICT_TOOLS)/Makefile.common

