FREEDICTDIR ?= ../../
DISTFILES = ChangeLog eng-tur.tei eng-tur.tei.header README ChangeLog ingtur-ing.utf8 \
	    ingtur-tur.utf8 eng-tur2tei.pl general.footer Makefile  \
      INSTALL freedict-P5.dtd freedict-P5.rng freedict-P5.xml freedict-dictionary.css
supported_phonetics=
include $(FREEDICTDIR)/tools/Makefile.common

#eng-tur-nophon.tei: eng-tur.tei.header ingtur-ing.utf8 \
#  ingtur-tur.utf8 eng-tur2tei.pl general.footer
#	cat eng-tur.tei.header >$@
#	./eng-tur2tei.pl >>$@
#	cat general.footer >>$@

#clean::
#	rm -f eng-tur-nophon.tei eng-tur.tei

