/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_app1 (void);
GtkWidget* create_about2 (void);
GtkWidget* create_fileselection1 (void);
GtkWidget* create_spellcheck_window (void);
GtkWidget* create_propertybox1 (void);
GtkWidget* create_sanity_window (void);
