/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <bonobo.h>
#include <gnome.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

static GnomeUIInfo file1_menu_uiinfo[] =
{
  GNOMEUIINFO_MENU_NEW_ITEM (N_("_New"), N_("New TEI File"), on_new1_activate, NULL),
  GNOMEUIINFO_MENU_OPEN_ITEM (on_open1_activate, NULL),
  GNOMEUIINFO_MENU_SAVE_ITEM (on_save1_activate, NULL),
  GNOMEUIINFO_MENU_SAVE_AS_ITEM (on_save_as1_activate, NULL),
  GNOMEUIINFO_SEPARATOR,
  GNOMEUIINFO_MENU_EXIT_ITEM (on_quit1_activate, NULL),
  GNOMEUIINFO_END
};

static GnomeUIInfo edit1_menu_uiinfo[] =
{
  GNOMEUIINFO_MENU_CUT_ITEM (on_cut1_activate, NULL),
  GNOMEUIINFO_MENU_COPY_ITEM (on_copy1_activate, NULL),
  GNOMEUIINFO_MENU_PASTE_ITEM (on_paste1_activate, NULL),
  GNOMEUIINFO_MENU_CLEAR_ITEM (on_clear1_activate, NULL),
  {
    GNOME_APP_UI_ITEM, N_("_Edit TEI Header"),
    N_("Edit information about the dictionary"),
    (gpointer) on_edit_header_activate, NULL, NULL,
    GNOME_APP_PIXMAP_STOCK, "gtk-properties",
    GDK_H, (GdkModifierType) GDK_CONTROL_MASK, NULL
  },
  {
    GNOME_APP_UI_ITEM, N_("_Spell Check..."),
    NULL,
    (gpointer) on_spell_check1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_STOCK, "gtk-spell-check",
    GDK_F7, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_ITEM, N_("S_anity Checks..."),
    N_("Find Entries with missing Information"),
    (gpointer) on_sanity_check_activate, NULL, NULL,
    GNOME_APP_PIXMAP_STOCK, "gtk-dialog-question",
    GDK_F8, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_SEPARATOR,
  GNOMEUIINFO_MENU_PREFERENCES_ITEM (on_preferences1_activate, NULL),
  GNOMEUIINFO_END
};

static GnomeUIInfo view1_menu_uiinfo[] =
{
  {
    GNOME_APP_UI_TOGGLEITEM, N_("Lock _Dockitems"),
    NULL,
    (gpointer) NULL, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_TOGGLEITEM, N_("_Labels"),
    N_("Toggle whether Labels are shown before Input fields"),
    (gpointer) NULL, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_TOGGLEITEM, N_("_Toolbar"),
    N_("Toggle Display of Toolbar"),
    (gpointer) NULL, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_TOGGLEITEM, N_("_HTML Preview"),
    N_("Toggle Display of HTML Preview Area"),
    (gpointer) NULL, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_ITEM, N_("_Keyboard Layout"),
    N_("Calls xkbprint to display current keyboard layout"),
    (gpointer) on_view_keyboard_layout_activate, NULL, NULL,
    GNOME_APP_PIXMAP_STOCK, "gnome-stock-midi",
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_END
};

static GnomeUIInfo help1_menu_uiinfo[] =
{
  GNOMEUIINFO_HELP ("freedict-editor"),
  {
    GNOME_APP_UI_ITEM, N_("Bonobo Experiment"),
    NULL,
    (gpointer) on_bonobo_experiment1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_STOCK, "gnome-stock-not",
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_MENU_ABOUT_ITEM (on_about1_activate, NULL),
  GNOMEUIINFO_END
};

static GnomeUIInfo menubar1_uiinfo[] =
{
  GNOMEUIINFO_MENU_FILE_TREE (file1_menu_uiinfo),
  GNOMEUIINFO_MENU_EDIT_TREE (edit1_menu_uiinfo),
  GNOMEUIINFO_MENU_VIEW_TREE (view1_menu_uiinfo),
  GNOMEUIINFO_MENU_HELP_TREE (help1_menu_uiinfo),
  GNOMEUIINFO_END
};

static GnomeUIInfo menu1_uiinfo[] =
{
  GNOMEUIINFO_END
};

static GnomeUIInfo menu2_uiinfo[] =
{
  {
    GNOME_APP_UI_ITEM, N_("_None"),
    NULL,
    (gpointer) NULL, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_ITEM, N_("_Singular"),
    NULL,
    (gpointer) NULL, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    GDK_i, (GdkModifierType) GDK_MOD1_MASK, NULL
  },
  {
    GNOME_APP_UI_ITEM, N_("_Dual"),
    NULL,
    (gpointer) NULL, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    GDK_u, (GdkModifierType) GDK_MOD1_MASK, NULL
  },
  {
    GNOME_APP_UI_ITEM, N_("_Plural"),
    NULL,
    (gpointer) NULL, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    GDK_p, (GdkModifierType) GDK_MOD1_MASK, NULL
  },
  GNOMEUIINFO_END
};

static GnomeUIInfo menu3_uiinfo[] =
{
  {
    GNOME_APP_UI_ITEM, N_("_None"),
    NULL,
    (gpointer) NULL, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_ITEM, N_("_Masculine"),
    NULL,
    (gpointer) NULL, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    GDK_m, (GdkModifierType) GDK_MOD1_MASK, NULL
  },
  {
    GNOME_APP_UI_ITEM, N_("_Feminine"),
    NULL,
    (gpointer) NULL, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    GDK_f, (GdkModifierType) GDK_MOD1_MASK, NULL
  },
  {
    GNOME_APP_UI_ITEM, N_("_Neuter"),
    NULL,
    (gpointer) NULL, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    GDK_e, (GdkModifierType) GDK_MOD1_MASK, NULL
  },
  GNOMEUIINFO_END
};

GtkWidget*
create_app1 (void)
{
  GtkWidget *app1;
  GdkPixbuf *app1_icon_pixbuf;
  GtkWidget *bonobodock1;
  GtkWidget *hbox18;
  GtkWidget *select_label;
  GtkWidget *entry3;
  GtkWidget *select_entry;
  GtkWidget *hbox19;
  GtkWidget *xpath_template_label;
  GtkWidget *entry4;
  GtkWidget *xpath_entry;
  GtkWidget *toolbar1;
  GtkWidget *new_file_button;
  GtkWidget *openbutton;
  GtkWidget *save_button;
  GtkWidget *tmp_toolbar_icon;
  GtkWidget *new_entry_button;
  GtkWidget *delete_button;
  GtkWidget *apply_button;
  GtkWidget *cancel_edit_button;
  GtkWidget *hpaned1;
  GtkWidget *frame1;
  GtkWidget *scrolledwindow2;
  GtkWidget *viewport1;
  GtkWidget *scrolledwindow3;
  GtkWidget *treeview1;
  GtkWidget *label4;
  GtkWidget *vpaned1;
  GtkWidget *notebook1;
  GtkWidget *scrolledwindow4;
  GtkWidget *textview1;
  GtkWidget *xml_view_label;
  GtkWidget *vbox4;
  GtkWidget *frame4;
  GtkWidget *table1;
  GtkWidget *orth_label;
  GtkWidget *entry1;
  GtkWidget *pron_label;
  GtkWidget *entry2;
  GtkWidget *hbox13;
  GtkWidget *pos_label;
  GtkWidget *pos_optionmenu;
  GtkWidget *menu1;
  GtkWidget *num_label;
  GtkWidget *num_optionmenu;
  GtkWidget *menu2;
  GtkWidget *gen_label;
  GtkWidget *gen_optionmenu;
  GtkWidget *menu3;
  GtkWidget *label12;
  GtkWidget *frame6;
  GtkWidget *senses_scrolledwindow;
  GtkWidget *viewport2;
  GtkWidget *vbox6;
  GtkWidget *sense_hbuttonbox;
  GtkWidget *add_sense_button;
  GtkWidget *remove_sense_button;
  GtkWidget *label11;
  GtkWidget *form_view_label;
  GtkWidget *appbar1;
  GtkAccelGroup *accel_group;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  accel_group = gtk_accel_group_new ();

  app1 = gnome_app_new ("FreeDict-Editor", _("FreeDict-Editor"));
  gtk_window_set_default_size (GTK_WINDOW (app1), 900, 670);
  gtk_window_set_destroy_with_parent (GTK_WINDOW (app1), TRUE);
  app1_icon_pixbuf = create_pixbuf ("freedict-editor/freedict.png");
  if (app1_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (app1), app1_icon_pixbuf);
      gdk_pixbuf_unref (app1_icon_pixbuf);
    }

  bonobodock1 = GNOME_APP (app1)->dock;
  gtk_widget_show (bonobodock1);

  gnome_app_create_menus (GNOME_APP (app1), menubar1_uiinfo);

  gtk_check_menu_item_set_active (GTK_CHECK_MENU_ITEM (view1_menu_uiinfo[1].widget), TRUE);

  gtk_check_menu_item_set_active (GTK_CHECK_MENU_ITEM (view1_menu_uiinfo[2].widget), TRUE);

  gtk_check_menu_item_set_active (GTK_CHECK_MENU_ITEM (view1_menu_uiinfo[3].widget), TRUE);

  gtk_widget_set_sensitive (help1_menu_uiinfo[1].widget, FALSE);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gnome_app_add_docked (GNOME_APP (app1), hbox18, "hbox18",
                                BONOBO_DOCK_ITEM_BEH_NEVER_VERTICAL,
                                BONOBO_DOCK_TOP, 1, 0, 0);

  select_label = gtk_label_new_with_mnemonic (_("Se_lect:"));
  gtk_widget_show (select_label);
  gtk_box_pack_start (GTK_BOX (hbox18), select_label, FALSE, FALSE, 2);
  gtk_label_set_justify (GTK_LABEL (select_label), GTK_JUSTIFY_LEFT);

  entry3 = gnome_entry_new ("Select");
  gtk_widget_show (entry3);
  gtk_box_pack_start (GTK_BOX (hbox18), entry3, TRUE, TRUE, 2);

  select_entry = gnome_entry_gtk_entry (GNOME_ENTRY (entry3));
  gtk_widget_show (select_entry);
  gtk_tooltips_set_tip (tooltips, select_entry, _("This string will replace the %s in the XPath-Template."), NULL);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gnome_app_add_docked (GNOME_APP (app1), hbox19, "hbox19",
                                BONOBO_DOCK_ITEM_BEH_NEVER_VERTICAL,
                                BONOBO_DOCK_TOP, 1, 1, 0);

  xpath_template_label = gtk_label_new_with_mnemonic (_("XPath-T_emplate:"));
  gtk_widget_show (xpath_template_label);
  gtk_box_pack_start (GTK_BOX (hbox19), xpath_template_label, FALSE, FALSE, 2);
  gtk_label_set_justify (GTK_LABEL (xpath_template_label), GTK_JUSTIFY_LEFT);

  entry4 = gnome_entry_new ("XPath-Template");
  gtk_widget_show (entry4);
  gtk_box_pack_start (GTK_BOX (hbox19), entry4, TRUE, TRUE, 2);

  xpath_entry = gnome_entry_gtk_entry (GNOME_ENTRY (entry4));
  gtk_widget_show (xpath_entry);
  gtk_tooltips_set_tip (tooltips, xpath_entry, _("Enter an XPath expression. It may contain one %s, which will be filled by the contents of the \"Select\" input field."), NULL);
  gtk_entry_set_text (GTK_ENTRY (xpath_entry), _("/TEI.2/text/body/entry[position()>0 and contains(form/orth,'%s')]"));
  gtk_entry_set_width_chars (GTK_ENTRY (xpath_entry), 64);

  toolbar1 = gtk_toolbar_new ();
  gtk_widget_show (toolbar1);
  gnome_app_add_toolbar (GNOME_APP (app1), GTK_TOOLBAR (toolbar1), "toolbar1",
                                BONOBO_DOCK_ITEM_BEH_NORMAL,
                                BONOBO_DOCK_LEFT, 0, 0, 1);
  gtk_container_set_border_width (GTK_CONTAINER (toolbar1), 2);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar1), GTK_TOOLBAR_ICONS);
  gtk_toolbar_set_orientation (GTK_TOOLBAR (toolbar1), GTK_ORIENTATION_VERTICAL);

  new_file_button = gtk_toolbar_insert_stock (GTK_TOOLBAR (toolbar1),
                                "gtk-new",
                                "gtk-new",
                                NULL, NULL, NULL, -1);
  gtk_widget_show (new_file_button);

  openbutton = gtk_toolbar_insert_stock (GTK_TOOLBAR (toolbar1),
                                "gtk-open",
                                "gtk-open",
                                NULL, NULL, NULL, -1);
  gtk_widget_show (openbutton);

  save_button = gtk_toolbar_insert_stock (GTK_TOOLBAR (toolbar1),
                                "gtk-save",
                                "gtk-save",
                                NULL, NULL, NULL, -1);
  gtk_widget_show (save_button);

  gtk_toolbar_append_space (GTK_TOOLBAR (toolbar1));

  tmp_toolbar_icon = gtk_image_new_from_stock ("gtk-add", gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar1)));
  new_entry_button = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Ne_w Entry"),
                                _("Add new Entry"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_label_set_use_underline (GTK_LABEL (((GtkToolbarChild*) (g_list_last (GTK_TOOLBAR (toolbar1)->children)->data))->label), TRUE);
  gtk_widget_show (new_entry_button);

  tmp_toolbar_icon = gtk_image_new_from_stock ("gtk-remove", gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar1)));
  delete_button = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("_Delete Entry"),
                                _("Delete Entry"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_label_set_use_underline (GTK_LABEL (((GtkToolbarChild*) (g_list_last (GTK_TOOLBAR (toolbar1)->children)->data))->label), TRUE);
  gtk_widget_show (delete_button);
  gtk_widget_set_sensitive (delete_button, FALSE);

  tmp_toolbar_icon = gtk_image_new_from_stock ("gtk-apply", gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar1)));
  apply_button = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Sa_ve Entry"),
                                _("Save changes to Entry"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_label_set_use_underline (GTK_LABEL (((GtkToolbarChild*) (g_list_last (GTK_TOOLBAR (toolbar1)->children)->data))->label), TRUE);
  gtk_widget_show (apply_button);
  gtk_widget_add_accelerator (apply_button, "activate", accel_group,
                              GDK_Return, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  tmp_toolbar_icon = gtk_image_new_from_stock ("gtk-cancel", gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar1)));
  cancel_edit_button = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("_Cancel Edit"),
                                _("Cancel Edit of Entry"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_label_set_use_underline (GTK_LABEL (((GtkToolbarChild*) (g_list_last (GTK_TOOLBAR (toolbar1)->children)->data))->label), TRUE);
  gtk_widget_show (cancel_edit_button);

  hpaned1 = gtk_hpaned_new ();
  gtk_widget_show (hpaned1);
  gnome_app_set_contents (GNOME_APP (app1), hpaned1);
  gtk_paned_set_position (GTK_PANED (hpaned1), 200);

  frame1 = gtk_frame_new (NULL);
  gtk_widget_show (frame1);
  gtk_paned_pack1 (GTK_PANED (hpaned1), frame1, FALSE, TRUE);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow2);
  gtk_container_add (GTK_CONTAINER (frame1), scrolledwindow2);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow2), GTK_POLICY_NEVER, GTK_POLICY_NEVER);

  viewport1 = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (viewport1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), viewport1);

  scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow3);
  gtk_container_add (GTK_CONTAINER (viewport1), scrolledwindow3);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow3), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow3), treeview1);
  gtk_tooltips_set_tip (tooltips, treeview1, _("Entries that match the select expression"), NULL);
  gtk_tree_view_set_headers_visible (GTK_TREE_VIEW (treeview1), FALSE);
  gtk_tree_view_set_rules_hint (GTK_TREE_VIEW (treeview1), TRUE);
  gtk_tree_view_set_reorderable (GTK_TREE_VIEW (treeview1), TRUE);

  label4 = gtk_label_new_with_mnemonic (_("En_tries"));
  gtk_widget_show (label4);
  gtk_frame_set_label_widget (GTK_FRAME (frame1), label4);
  gtk_label_set_justify (GTK_LABEL (label4), GTK_JUSTIFY_LEFT);

  vpaned1 = gtk_vpaned_new ();
  gtk_widget_show (vpaned1);
  gtk_paned_pack2 (GTK_PANED (hpaned1), vpaned1, TRUE, TRUE);
  gtk_paned_set_position (GTK_PANED (vpaned1), 480);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_paned_pack1 (GTK_PANED (vpaned1), notebook1, FALSE, TRUE);
  gtk_container_set_border_width (GTK_CONTAINER (notebook1), 3);
  gtk_notebook_set_show_border (GTK_NOTEBOOK (notebook1), FALSE);
  gtk_notebook_set_tab_pos (GTK_NOTEBOOK (notebook1), GTK_POS_RIGHT);

  scrolledwindow4 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow4);
  gtk_container_add (GTK_CONTAINER (notebook1), scrolledwindow4);
  gtk_notebook_set_menu_label_text (GTK_NOTEBOOK (notebook1), scrolledwindow4,
                                    _("XML View"));

  textview1 = gtk_text_view_new ();
  gtk_widget_show (textview1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow4), textview1);
  gtk_tooltips_set_tip (tooltips, textview1, _("The XML edit mode is selected of the entry cannot be edited with the formular."), NULL);

  xml_view_label = gtk_label_new_with_mnemonic (_("_XML"));
  gtk_widget_show (xml_view_label);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), xml_view_label);
  gtk_label_set_justify (GTK_LABEL (xml_view_label), GTK_JUSTIFY_LEFT);

  vbox4 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox4);
  gtk_container_add (GTK_CONTAINER (notebook1), vbox4);
  gtk_container_set_border_width (GTK_CONTAINER (vbox4), 3);

  frame4 = gtk_frame_new (NULL);
  gtk_widget_show (frame4);
  gtk_box_pack_start (GTK_BOX (vbox4), frame4, FALSE, TRUE, 0);

  table1 = gtk_table_new (2, 4, FALSE);
  gtk_widget_show (table1);
  gtk_container_add (GTK_CONTAINER (frame4), table1);
  gtk_container_set_border_width (GTK_CONTAINER (table1), 10);
  gtk_table_set_row_spacings (GTK_TABLE (table1), 5);
  gtk_table_set_col_spacings (GTK_TABLE (table1), 5);

  orth_label = gtk_label_new_with_mnemonic (_("_Orthography"));
  gtk_widget_show (orth_label);
  gtk_table_attach (GTK_TABLE (table1), orth_label, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (orth_label), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (orth_label), 0, 0.5);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_table_attach (GTK_TABLE (table1), entry1, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, entry1, _("How the word is written"), NULL);

  pron_label = gtk_label_new_with_mnemonic (_("_Pronunciation"));
  gtk_widget_show (pron_label);
  gtk_table_attach (GTK_TABLE (table1), pron_label, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (pron_label), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (pron_label), 0, 0.5);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_table_attach (GTK_TABLE (table1), entry2, 3, 4, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, entry2, _("Please enter Unicode encoded characters of the International Phonetic Alphabet"), NULL);

  hbox13 = gtk_hbox_new (FALSE, 5);
  gtk_widget_show (hbox13);
  gtk_table_attach (GTK_TABLE (table1), hbox13, 0, 4, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  pos_label = gtk_label_new_with_mnemonic (_("Part of _Speech"));
  gtk_widget_show (pos_label);
  gtk_box_pack_start (GTK_BOX (hbox13), pos_label, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (pos_label), GTK_JUSTIFY_LEFT);

  pos_optionmenu = gtk_option_menu_new ();
  gtk_widget_show (pos_optionmenu);
  gtk_box_pack_start (GTK_BOX (hbox13), pos_optionmenu, TRUE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, pos_optionmenu, _("Part of Speech"), NULL);

  menu1 = gtk_menu_new ();
  gnome_app_fill_menu (GTK_MENU_SHELL (menu1), menu1_uiinfo,
                       NULL, FALSE, 0);

  gtk_option_menu_set_menu (GTK_OPTION_MENU (pos_optionmenu), menu1);

  num_label = gtk_label_new_with_mnemonic (_("_Number"));
  gtk_widget_show (num_label);
  gtk_box_pack_start (GTK_BOX (hbox13), num_label, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (num_label), GTK_JUSTIFY_LEFT);

  num_optionmenu = gtk_option_menu_new ();
  gtk_widget_show (num_optionmenu);
  gtk_box_pack_start (GTK_BOX (hbox13), num_optionmenu, TRUE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, num_optionmenu, _("Number"), NULL);
  gtk_widget_add_accelerator (num_optionmenu, "activate", accel_group,
                              GDK_s, GDK_CONTROL_MASK | GDK_SHIFT_MASK | GDK_MOD1_MASK,
                              GTK_ACCEL_VISIBLE);

  menu2 = gtk_menu_new ();
  gnome_app_fill_menu (GTK_MENU_SHELL (menu2), menu2_uiinfo,
                       NULL, FALSE, 0);

  gtk_option_menu_set_menu (GTK_OPTION_MENU (num_optionmenu), menu2);

  gen_label = gtk_label_new_with_mnemonic (_("_Genus"));
  gtk_widget_show (gen_label);
  gtk_box_pack_start (GTK_BOX (hbox13), gen_label, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (gen_label), GTK_JUSTIFY_LEFT);

  gen_optionmenu = gtk_option_menu_new ();
  gtk_widget_show (gen_optionmenu);
  gtk_box_pack_start (GTK_BOX (hbox13), gen_optionmenu, TRUE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, gen_optionmenu, _("Genus"), NULL);

  menu3 = gtk_menu_new ();
  gnome_app_fill_menu (GTK_MENU_SHELL (menu3), menu3_uiinfo,
                       NULL, FALSE, 0);

  gtk_option_menu_set_menu (GTK_OPTION_MENU (gen_optionmenu), menu3);

  label12 = gtk_label_new (_("Headword(s)"));
  gtk_widget_show (label12);
  gtk_frame_set_label_widget (GTK_FRAME (frame4), label12);
  gtk_label_set_justify (GTK_LABEL (label12), GTK_JUSTIFY_LEFT);

  frame6 = gtk_frame_new (NULL);
  gtk_widget_show (frame6);
  gtk_box_pack_start (GTK_BOX (vbox4), frame6, TRUE, TRUE, 0);

  senses_scrolledwindow = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (senses_scrolledwindow);
  gtk_container_add (GTK_CONTAINER (frame6), senses_scrolledwindow);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (senses_scrolledwindow), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  viewport2 = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (viewport2);
  gtk_container_add (GTK_CONTAINER (senses_scrolledwindow), viewport2);
  gtk_viewport_set_shadow_type (GTK_VIEWPORT (viewport2), GTK_SHADOW_NONE);

  vbox6 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox6);
  gtk_container_add (GTK_CONTAINER (viewport2), vbox6);

  sense_hbuttonbox = gtk_hbutton_box_new ();
  gtk_widget_show (sense_hbuttonbox);
  gtk_box_pack_end (GTK_BOX (vbox6), sense_hbuttonbox, FALSE, TRUE, 0);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (sense_hbuttonbox), GTK_BUTTONBOX_SPREAD);

  add_sense_button = gtk_button_new_from_stock ("gtk-add");
  gtk_widget_show (add_sense_button);
  gtk_container_add (GTK_CONTAINER (sense_hbuttonbox), add_sense_button);
  GTK_WIDGET_SET_FLAGS (add_sense_button, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, add_sense_button, _("Append new Sense to Entry"), NULL);

  remove_sense_button = gtk_button_new_from_stock ("gtk-remove");
  gtk_widget_show (remove_sense_button);
  gtk_container_add (GTK_CONTAINER (sense_hbuttonbox), remove_sense_button);
  GTK_WIDGET_SET_FLAGS (remove_sense_button, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, remove_sense_button, _("Remove last Sense from Entry"), NULL);

  label11 = gtk_label_new (_("Sense(s)"));
  gtk_widget_show (label11);
  gtk_frame_set_label_widget (GTK_FRAME (frame6), label11);
  gtk_label_set_justify (GTK_LABEL (label11), GTK_JUSTIFY_LEFT);

  form_view_label = gtk_label_new_with_mnemonic (_("For_m"));
  gtk_widget_show (form_view_label);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), form_view_label);
  gtk_label_set_justify (GTK_LABEL (form_view_label), GTK_JUSTIFY_LEFT);

  appbar1 = gnome_appbar_new (FALSE, TRUE, GNOME_PREFERENCES_NEVER);
  gtk_widget_show (appbar1);
  gnome_app_set_statusbar (GNOME_APP (app1), appbar1);

  g_signal_connect ((gpointer) app1, "delete_event",
                    G_CALLBACK (on_app1_delete_event),
                    NULL);
  g_signal_connect ((gpointer) app1, "show",
                    G_CALLBACK (on_app1_show),
                    NULL);
  g_signal_connect ((gpointer) app1, "drag_data_received",
                    G_CALLBACK (on_app1_drag_data_received),
                    NULL);
  gnome_app_install_menu_hints (GNOME_APP (app1), menubar1_uiinfo);
  g_signal_connect ((gpointer) select_entry, "changed",
                    G_CALLBACK (on_select_entry_changed),
                    NULL);
  g_signal_connect ((gpointer) new_file_button, "clicked",
                    G_CALLBACK (on_new_file_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) openbutton, "clicked",
                    G_CALLBACK (on_openbutton_clicked),
                    NULL);
  g_signal_connect ((gpointer) save_button, "clicked",
                    G_CALLBACK (on_save_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) new_entry_button, "clicked",
                    G_CALLBACK (on_new_entry_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) delete_button, "clicked",
                    G_CALLBACK (on_delete_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) apply_button, "clicked",
                    G_CALLBACK (on_apply_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) cancel_edit_button, "clicked",
                    G_CALLBACK (on_cancel_edit_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview1, "row_activated",
                    G_CALLBACK (on_treeview1_row_activated),
                    NULL);
  g_signal_connect ((gpointer) treeview1, "cursor_changed",
                    G_CALLBACK (on_treeview1_cursor_changed),
                    NULL);
  g_signal_connect ((gpointer) notebook1, "switch_page",
                    G_CALLBACK (on_notebook1_switch_page),
                    NULL);
  g_signal_connect ((gpointer) entry1, "changed",
                    G_CALLBACK (on_form_entry_changed),
                    NULL);
  g_signal_connect ((gpointer) entry2, "changed",
                    G_CALLBACK (on_form_entry_changed),
                    NULL);
  g_signal_connect_swapped ((gpointer) entry2, "focus_in_event",
                            G_CALLBACK (on_entry2_focus_in_event),
                            GTK_OBJECT (entry2));
  g_signal_connect_swapped ((gpointer) entry2, "focus_out_event",
                            G_CALLBACK (on_entry2_focus_out_event),
                            GTK_OBJECT (entry2));
  g_signal_connect ((gpointer) pos_optionmenu, "changed",
                    G_CALLBACK (on_form_optionmenu_changed),
                    NULL);
  g_signal_connect ((gpointer) num_optionmenu, "changed",
                    G_CALLBACK (on_form_optionmenu_changed),
                    NULL);
  g_signal_connect ((gpointer) gen_optionmenu, "changed",
                    G_CALLBACK (on_form_optionmenu_changed),
                    NULL);
  g_signal_connect ((gpointer) add_sense_button, "clicked",
                    G_CALLBACK (on_add_sense_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) remove_sense_button, "clicked",
                    G_CALLBACK (on_remove_sense_button_clicked),
                    NULL);

  gtk_label_set_mnemonic_widget (GTK_LABEL (select_label), select_entry);
  gtk_label_set_mnemonic_widget (GTK_LABEL (xpath_template_label), xpath_entry);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label4), treeview1);
  gtk_label_set_mnemonic_widget (GTK_LABEL (orth_label), entry1);
  gtk_label_set_mnemonic_widget (GTK_LABEL (pron_label), entry2);
  gtk_label_set_mnemonic_widget (GTK_LABEL (pos_label), pos_optionmenu);
  gtk_label_set_mnemonic_widget (GTK_LABEL (num_label), num_optionmenu);
  gtk_label_set_mnemonic_widget (GTK_LABEL (gen_label), gen_optionmenu);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (app1, app1, "app1");
  GLADE_HOOKUP_OBJECT (app1, bonobodock1, "bonobodock1");
  GLADE_HOOKUP_OBJECT (app1, menubar1_uiinfo[0].widget, "file1");
  GLADE_HOOKUP_OBJECT (app1, file1_menu_uiinfo[0].widget, "new1");
  GLADE_HOOKUP_OBJECT (app1, file1_menu_uiinfo[1].widget, "open1");
  GLADE_HOOKUP_OBJECT (app1, file1_menu_uiinfo[2].widget, "save1");
  GLADE_HOOKUP_OBJECT (app1, file1_menu_uiinfo[3].widget, "save_as1");
  GLADE_HOOKUP_OBJECT (app1, file1_menu_uiinfo[4].widget, "separator3");
  GLADE_HOOKUP_OBJECT (app1, file1_menu_uiinfo[5].widget, "quit1");
  GLADE_HOOKUP_OBJECT (app1, menubar1_uiinfo[1].widget, "edit1");
  GLADE_HOOKUP_OBJECT (app1, edit1_menu_uiinfo[0].widget, "cut1");
  GLADE_HOOKUP_OBJECT (app1, edit1_menu_uiinfo[1].widget, "copy1");
  GLADE_HOOKUP_OBJECT (app1, edit1_menu_uiinfo[2].widget, "paste1");
  GLADE_HOOKUP_OBJECT (app1, edit1_menu_uiinfo[3].widget, "clear1");
  GLADE_HOOKUP_OBJECT (app1, edit1_menu_uiinfo[4].widget, "edit_header");
  GLADE_HOOKUP_OBJECT (app1, edit1_menu_uiinfo[5].widget, "spell_check1");
  GLADE_HOOKUP_OBJECT (app1, edit1_menu_uiinfo[6].widget, "sanity_check");
  GLADE_HOOKUP_OBJECT (app1, edit1_menu_uiinfo[7].widget, "separator5");
  GLADE_HOOKUP_OBJECT (app1, edit1_menu_uiinfo[8].widget, "preferences1");
  GLADE_HOOKUP_OBJECT (app1, menubar1_uiinfo[2].widget, "view1");
  GLADE_HOOKUP_OBJECT (app1, view1_menu_uiinfo[0].widget, "lock_dockitems");
  GLADE_HOOKUP_OBJECT (app1, view1_menu_uiinfo[1].widget, "view_labels");
  GLADE_HOOKUP_OBJECT (app1, view1_menu_uiinfo[2].widget, "view_toolbar");
  GLADE_HOOKUP_OBJECT (app1, view1_menu_uiinfo[3].widget, "view_html");
  GLADE_HOOKUP_OBJECT (app1, view1_menu_uiinfo[4].widget, "view_keyboard_layout");
  GLADE_HOOKUP_OBJECT (app1, menubar1_uiinfo[3].widget, "help1");
  GLADE_HOOKUP_OBJECT (app1, help1_menu_uiinfo[1].widget, "bonobo_experiment1");
  GLADE_HOOKUP_OBJECT (app1, help1_menu_uiinfo[2].widget, "about1");
  GLADE_HOOKUP_OBJECT (app1, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (app1, select_label, "select_label");
  GLADE_HOOKUP_OBJECT (app1, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (app1, select_entry, "select_entry");
  GLADE_HOOKUP_OBJECT (app1, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (app1, xpath_template_label, "xpath_template_label");
  GLADE_HOOKUP_OBJECT (app1, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (app1, xpath_entry, "xpath_entry");
  GLADE_HOOKUP_OBJECT (app1, toolbar1, "toolbar1");
  GLADE_HOOKUP_OBJECT (app1, new_file_button, "new_file_button");
  GLADE_HOOKUP_OBJECT (app1, openbutton, "openbutton");
  GLADE_HOOKUP_OBJECT (app1, save_button, "save_button");
  GLADE_HOOKUP_OBJECT (app1, new_entry_button, "new_entry_button");
  GLADE_HOOKUP_OBJECT (app1, delete_button, "delete_button");
  GLADE_HOOKUP_OBJECT (app1, apply_button, "apply_button");
  GLADE_HOOKUP_OBJECT (app1, cancel_edit_button, "cancel_edit_button");
  GLADE_HOOKUP_OBJECT (app1, hpaned1, "hpaned1");
  GLADE_HOOKUP_OBJECT (app1, frame1, "frame1");
  GLADE_HOOKUP_OBJECT (app1, scrolledwindow2, "scrolledwindow2");
  GLADE_HOOKUP_OBJECT (app1, viewport1, "viewport1");
  GLADE_HOOKUP_OBJECT (app1, scrolledwindow3, "scrolledwindow3");
  GLADE_HOOKUP_OBJECT (app1, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (app1, label4, "label4");
  GLADE_HOOKUP_OBJECT (app1, vpaned1, "vpaned1");
  GLADE_HOOKUP_OBJECT (app1, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (app1, scrolledwindow4, "scrolledwindow4");
  GLADE_HOOKUP_OBJECT (app1, textview1, "textview1");
  GLADE_HOOKUP_OBJECT (app1, xml_view_label, "xml_view_label");
  GLADE_HOOKUP_OBJECT (app1, vbox4, "vbox4");
  GLADE_HOOKUP_OBJECT (app1, frame4, "frame4");
  GLADE_HOOKUP_OBJECT (app1, table1, "table1");
  GLADE_HOOKUP_OBJECT (app1, orth_label, "orth_label");
  GLADE_HOOKUP_OBJECT (app1, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (app1, pron_label, "pron_label");
  GLADE_HOOKUP_OBJECT (app1, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (app1, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (app1, pos_label, "pos_label");
  GLADE_HOOKUP_OBJECT (app1, pos_optionmenu, "pos_optionmenu");
  GLADE_HOOKUP_OBJECT (app1, menu1, "menu1");
  GLADE_HOOKUP_OBJECT (app1, num_label, "num_label");
  GLADE_HOOKUP_OBJECT (app1, num_optionmenu, "num_optionmenu");
  GLADE_HOOKUP_OBJECT (app1, menu2, "menu2");
  GLADE_HOOKUP_OBJECT (app1, menu2_uiinfo[0].widget, "none");
  GLADE_HOOKUP_OBJECT (app1, menu2_uiinfo[1].widget, "s");
  GLADE_HOOKUP_OBJECT (app1, menu2_uiinfo[2].widget, "du");
  GLADE_HOOKUP_OBJECT (app1, menu2_uiinfo[3].widget, "pl");
  GLADE_HOOKUP_OBJECT (app1, gen_label, "gen_label");
  GLADE_HOOKUP_OBJECT (app1, gen_optionmenu, "gen_optionmenu");
  GLADE_HOOKUP_OBJECT (app1, menu3, "menu3");
  GLADE_HOOKUP_OBJECT (app1, menu3_uiinfo[0].widget, "none");
  GLADE_HOOKUP_OBJECT (app1, menu3_uiinfo[1].widget, "m");
  GLADE_HOOKUP_OBJECT (app1, menu3_uiinfo[2].widget, "f");
  GLADE_HOOKUP_OBJECT (app1, menu3_uiinfo[3].widget, "n");
  GLADE_HOOKUP_OBJECT (app1, label12, "label12");
  GLADE_HOOKUP_OBJECT (app1, frame6, "frame6");
  GLADE_HOOKUP_OBJECT (app1, senses_scrolledwindow, "senses_scrolledwindow");
  GLADE_HOOKUP_OBJECT (app1, viewport2, "viewport2");
  GLADE_HOOKUP_OBJECT (app1, vbox6, "vbox6");
  GLADE_HOOKUP_OBJECT (app1, sense_hbuttonbox, "sense_hbuttonbox");
  GLADE_HOOKUP_OBJECT (app1, add_sense_button, "add_sense_button");
  GLADE_HOOKUP_OBJECT (app1, remove_sense_button, "remove_sense_button");
  GLADE_HOOKUP_OBJECT (app1, label11, "label11");
  GLADE_HOOKUP_OBJECT (app1, form_view_label, "form_view_label");
  GLADE_HOOKUP_OBJECT (app1, appbar1, "appbar1");
  GLADE_HOOKUP_OBJECT_NO_REF (app1, tooltips, "tooltips");

  gtk_widget_grab_focus (select_entry);
  gtk_window_add_accel_group (GTK_WINDOW (app1), accel_group);

  return app1;
}

GtkWidget*
create_about2 (void)
{
  const gchar *authors[] = {
    "Michael Bunk <micha@luetzschena.de>",
    NULL
  };
  const gchar *documenters[] = { NULL };
  /* TRANSLATORS: Replace this string with your names, one name per line. */
  gchar *translators = _("translator_credits");
  GtkWidget *about2;
  GdkPixbuf *about2_icon_pixbuf;

  if (!strcmp (translators, "translator_credits"))
    translators = NULL;
  about2 = gnome_about_new ("FreeDict-Editor", VERSION,
                        _("FreeDict Project, freedict.org, 2005"),
                        "",
                        authors,
                        documenters,
                        translators,
                        NULL);
  gtk_window_set_destroy_with_parent (GTK_WINDOW (about2), TRUE);
  about2_icon_pixbuf = create_pixbuf ("freedict-editor/freedict.gif");
  if (about2_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (about2), about2_icon_pixbuf);
      gdk_pixbuf_unref (about2_icon_pixbuf);
    }

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (about2, about2, "about2");

  return about2;
}

GtkWidget*
create_fileselection1 (void)
{
  GtkWidget *fileselection1;
  GtkWidget *ok_button1;
  GtkWidget *cancel_button1;

  fileselection1 = gtk_file_selection_new (_("Select File"));
  gtk_container_set_border_width (GTK_CONTAINER (fileselection1), 10);
  gtk_window_set_modal (GTK_WINDOW (fileselection1), TRUE);

  ok_button1 = GTK_FILE_SELECTION (fileselection1)->ok_button;
  gtk_widget_show (ok_button1);
  GTK_WIDGET_SET_FLAGS (ok_button1, GTK_CAN_DEFAULT);

  cancel_button1 = GTK_FILE_SELECTION (fileselection1)->cancel_button;
  gtk_widget_show (cancel_button1);
  GTK_WIDGET_SET_FLAGS (cancel_button1, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) fileselection1, "close",
                    G_CALLBACK (gtk_widget_destroy),
                    NULL);
  g_signal_connect ((gpointer) ok_button1, "clicked",
                    G_CALLBACK (on_ok_button1_clicked),
                    NULL);
  g_signal_connect ((gpointer) cancel_button1, "clicked",
                    G_CALLBACK (on_cancel_button1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (fileselection1, fileselection1, "fileselection1");
  GLADE_HOOKUP_OBJECT_NO_REF (fileselection1, ok_button1, "ok_button1");
  GLADE_HOOKUP_OBJECT_NO_REF (fileselection1, cancel_button1, "cancel_button1");

  return fileselection1;
}

GtkWidget*
create_spellcheck_window (void)
{
  GtkWidget *spellcheck_window;
  GtkWidget *hbox14;
  GtkWidget *table2;
  GtkWidget *misspelled_word_label;
  GtkWidget *misspelled_word_entry;
  GtkWidget *replacement_label;
  GtkWidget *replacement_entry;
  GtkWidget *suggestions_label;
  GtkWidget *label50;
  GtkWidget *spell_dict_combo;
  GtkWidget *check_dict_combo_entry;
  GtkWidget *vbox7;
  GtkWidget *spell_orth_checkbutton;
  GtkWidget *spell_tr_checkbutton;
  GtkWidget *spell_eg_checkbutton;
  GtkWidget *spell_eg_tr_checkbutton;
  GtkWidget *hbox17;
  GtkWidget *spell_headwords_radiobutton;
  GSList *spell_headwords_radiobutton_group = NULL;
  GtkWidget *spell_translations_radiobutton;
  GtkWidget *label49;
  GtkWidget *scrolledwindow5;
  GtkWidget *suggestions_treeview;
  GtkWidget *spell_progressbar;
  GtkWidget *vbuttonbox1;
  GtkWidget *spell_replace_button;
  GtkWidget *alignment7;
  GtkWidget *hbox15;
  GtkWidget *image9;
  GtkWidget *label47;
  GtkWidget *spell_replace_all_button;
  GtkWidget *spell_ignore_button;
  GtkWidget *alignment8;
  GtkWidget *hbox16;
  GtkWidget *image10;
  GtkWidget *label48;
  GtkWidget *spell_ignore_all_button;
  GtkWidget *spell_add_button;
  GtkWidget *spell_close_button;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  spellcheck_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (spellcheck_window), _("Spell Check"));
  gtk_window_set_modal (GTK_WINDOW (spellcheck_window), TRUE);

  hbox14 = gtk_hbox_new (FALSE, 7);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (spellcheck_window), hbox14);
  gtk_container_set_border_width (GTK_CONTAINER (hbox14), 7);

  table2 = gtk_table_new (7, 2, FALSE);
  gtk_widget_show (table2);
  gtk_box_pack_start (GTK_BOX (hbox14), table2, TRUE, TRUE, 0);
  gtk_table_set_row_spacings (GTK_TABLE (table2), 4);
  gtk_table_set_col_spacings (GTK_TABLE (table2), 4);

  misspelled_word_label = gtk_label_new (_("Misspelled word:"));
  gtk_widget_show (misspelled_word_label);
  gtk_table_attach (GTK_TABLE (table2), misspelled_word_label, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (misspelled_word_label), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (misspelled_word_label), 0, 0.5);

  misspelled_word_entry = gtk_entry_new ();
  gtk_widget_show (misspelled_word_entry);
  gtk_table_attach (GTK_TABLE (table2), misspelled_word_entry, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_sensitive (misspelled_word_entry, FALSE);
  gtk_tooltips_set_tip (tooltips, misspelled_word_entry, _("A word that was not found in the spelling dictionary"), NULL);
  gtk_editable_set_editable (GTK_EDITABLE (misspelled_word_entry), FALSE);

  replacement_label = gtk_label_new (_("Replacement:"));
  gtk_widget_show (replacement_label);
  gtk_table_attach (GTK_TABLE (table2), replacement_label, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (replacement_label), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (replacement_label), 0, 0.5);

  replacement_entry = gtk_entry_new ();
  gtk_widget_show (replacement_entry);
  gtk_table_attach (GTK_TABLE (table2), replacement_entry, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_activates_default (GTK_ENTRY (replacement_entry), TRUE);

  suggestions_label = gtk_label_new (_("Suggestions:"));
  gtk_widget_show (suggestions_label);
  gtk_table_attach (GTK_TABLE (table2), suggestions_label, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (suggestions_label), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (suggestions_label), 0, 0.5);

  label50 = gtk_label_new (_("Spelling Dictionary:"));
  gtk_widget_show (label50);
  gtk_table_attach (GTK_TABLE (table2), label50, 0, 1, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label50), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label50), 0, 0.5);

  spell_dict_combo = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (spell_dict_combo)->popwin),
                     "GladeParentKey", spell_dict_combo);
  gtk_widget_show (spell_dict_combo);
  gtk_table_attach (GTK_TABLE (table2), spell_dict_combo, 1, 2, 5, 6,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_combo_set_value_in_list (GTK_COMBO (spell_dict_combo), TRUE, FALSE);

  check_dict_combo_entry = GTK_COMBO (spell_dict_combo)->entry;
  gtk_widget_show (check_dict_combo_entry);
  gtk_tooltips_set_tip (tooltips, check_dict_combo_entry, _("What lnagugae to use for checking the words"), NULL);
  gtk_editable_set_editable (GTK_EDITABLE (check_dict_combo_entry), FALSE);

  vbox7 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox7);
  gtk_table_attach (GTK_TABLE (table2), vbox7, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  spell_orth_checkbutton = gtk_check_button_new_with_mnemonic (_("<orth> - Headwords"));
  gtk_widget_show (spell_orth_checkbutton);
  gtk_box_pack_start (GTK_BOX (vbox7), spell_orth_checkbutton, FALSE, FALSE, 0);

  spell_tr_checkbutton = gtk_check_button_new_with_mnemonic (_("<tr> - Translations"));
  gtk_widget_show (spell_tr_checkbutton);
  gtk_box_pack_start (GTK_BOX (vbox7), spell_tr_checkbutton, FALSE, FALSE, 0);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (spell_tr_checkbutton), TRUE);

  spell_eg_checkbutton = gtk_check_button_new_with_mnemonic (_("<eg><q> - Quotes of Examples"));
  gtk_widget_show (spell_eg_checkbutton);
  gtk_box_pack_start (GTK_BOX (vbox7), spell_eg_checkbutton, FALSE, FALSE, 0);

  spell_eg_tr_checkbutton = gtk_check_button_new_with_mnemonic (_("<eg><tr> - Translations of Examples"));
  gtk_widget_show (spell_eg_tr_checkbutton);
  gtk_box_pack_start (GTK_BOX (vbox7), spell_eg_tr_checkbutton, FALSE, FALSE, 0);

  hbox17 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox17);
  gtk_table_attach (GTK_TABLE (table2), hbox17, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  spell_headwords_radiobutton = gtk_radio_button_new_with_mnemonic (NULL, _("_Headword Language"));
  gtk_widget_show (spell_headwords_radiobutton);
  gtk_box_pack_start (GTK_BOX (hbox17), spell_headwords_radiobutton, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (spell_headwords_radiobutton), spell_headwords_radiobutton_group);
  spell_headwords_radiobutton_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (spell_headwords_radiobutton));

  spell_translations_radiobutton = gtk_radio_button_new_with_mnemonic (NULL, _("_Translation Language"));
  gtk_widget_show (spell_translations_radiobutton);
  gtk_box_pack_start (GTK_BOX (hbox17), spell_translations_radiobutton, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (spell_translations_radiobutton), spell_headwords_radiobutton_group);
  spell_headwords_radiobutton_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (spell_translations_radiobutton));
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (spell_translations_radiobutton), TRUE);

  label49 = gtk_label_new (_("Check:"));
  gtk_widget_show (label49);
  gtk_table_attach (GTK_TABLE (table2), label49, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label49), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label49), 0, 0.5);

  scrolledwindow5 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow5);
  gtk_table_attach (GTK_TABLE (table2), scrolledwindow5, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);
  gtk_widget_set_size_request (scrolledwindow5, 41, 140);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow5), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow5), GTK_SHADOW_IN);

  suggestions_treeview = gtk_tree_view_new ();
  gtk_widget_show (suggestions_treeview);
  gtk_container_add (GTK_CONTAINER (scrolledwindow5), suggestions_treeview);
  gtk_tooltips_set_tip (tooltips, suggestions_treeview, _("Double-Click to replace the misspelled word with a suggestion"), NULL);
  gtk_tree_view_set_headers_visible (GTK_TREE_VIEW (suggestions_treeview), FALSE);
  gtk_tree_view_set_rules_hint (GTK_TREE_VIEW (suggestions_treeview), TRUE);

  spell_progressbar = gtk_progress_bar_new ();
  gtk_widget_show (spell_progressbar);
  gtk_table_attach (GTK_TABLE (table2), spell_progressbar, 0, 2, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_progress_bar_set_text (GTK_PROGRESS_BAR (spell_progressbar), _("Nodes checked"));

  vbuttonbox1 = gtk_vbutton_box_new ();
  gtk_widget_show (vbuttonbox1);
  gtk_box_pack_start (GTK_BOX (hbox14), vbuttonbox1, TRUE, TRUE, 0);

  spell_replace_button = gtk_button_new ();
  gtk_widget_show (spell_replace_button);
  gtk_container_add (GTK_CONTAINER (vbuttonbox1), spell_replace_button);
  GTK_WIDGET_SET_FLAGS (spell_replace_button, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, spell_replace_button, _("Replace misspelled word with replacement or suggestion"), NULL);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (spell_replace_button), alignment7);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox15);

  image9 = gtk_image_new_from_stock ("gtk-spell-check", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox15), image9, FALSE, FALSE, 0);

  label47 = gtk_label_new_with_mnemonic (_("_Replace"));
  gtk_widget_show (label47);
  gtk_box_pack_start (GTK_BOX (hbox15), label47, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label47), GTK_JUSTIFY_LEFT);

  spell_replace_all_button = gtk_button_new_with_mnemonic (_("Replace _All"));
  gtk_widget_show (spell_replace_all_button);
  gtk_container_add (GTK_CONTAINER (vbuttonbox1), spell_replace_all_button);
  GTK_WIDGET_SET_FLAGS (spell_replace_all_button, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, spell_replace_all_button, _("Replace all occurences of the misspelled word with replacement or selected suggestion"), NULL);

  spell_ignore_button = gtk_button_new ();
  gtk_widget_show (spell_ignore_button);
  gtk_container_add (GTK_CONTAINER (vbuttonbox1), spell_ignore_button);
  GTK_WIDGET_SET_FLAGS (spell_ignore_button, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, spell_ignore_button, _("Ignore the occurence of a misspelled word"), NULL);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (spell_ignore_button), alignment8);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox16);

  image10 = gtk_image_new_from_stock ("gtk-go-forward", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox16), image10, FALSE, FALSE, 0);

  label48 = gtk_label_new_with_mnemonic (_("_Ignore"));
  gtk_widget_show (label48);
  gtk_box_pack_start (GTK_BOX (hbox16), label48, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label48), GTK_JUSTIFY_LEFT);

  spell_ignore_all_button = gtk_button_new_with_mnemonic (_("I_gnore All"));
  gtk_widget_show (spell_ignore_all_button);
  gtk_container_add (GTK_CONTAINER (vbuttonbox1), spell_ignore_all_button);
  GTK_WIDGET_SET_FLAGS (spell_ignore_all_button, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, spell_ignore_all_button, _("Ignore all occurences of this misspelled word"), NULL);

  spell_add_button = gtk_button_new_from_stock ("gtk-add");
  gtk_widget_show (spell_add_button);
  gtk_container_add (GTK_CONTAINER (vbuttonbox1), spell_add_button);
  GTK_WIDGET_SET_FLAGS (spell_add_button, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, spell_add_button, _("Add this word to the personal word list of this language"), NULL);

  spell_close_button = gtk_button_new_from_stock ("gtk-close");
  gtk_widget_show (spell_close_button);
  gtk_container_add (GTK_CONTAINER (vbuttonbox1), spell_close_button);
  GTK_WIDGET_SET_FLAGS (spell_close_button, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) spell_headwords_radiobutton, "toggled",
                    G_CALLBACK (on_spell_headwords_radiobutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) spell_translations_radiobutton, "toggled",
                    G_CALLBACK (on_spell_translations_radiobutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) suggestions_treeview, "row_activated",
                    G_CALLBACK (on_suggestions_treeview_row_activated),
                    NULL);
  g_signal_connect ((gpointer) suggestions_treeview, "cursor_changed",
                    G_CALLBACK (on_suggestions_treeview_cursor_changed),
                    NULL);
  g_signal_connect ((gpointer) spell_replace_button, "clicked",
                    G_CALLBACK (on_spell_replace_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) spell_replace_all_button, "clicked",
                    G_CALLBACK (on_spell_replace_all_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) spell_ignore_button, "clicked",
                    G_CALLBACK (on_spell_ignore_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) spell_ignore_all_button, "clicked",
                    G_CALLBACK (on_spell_ignore_all_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) spell_add_button, "clicked",
                    G_CALLBACK (on_spell_add_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) spell_close_button, "clicked",
                    G_CALLBACK (on_spell_close_button_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (spellcheck_window, spellcheck_window, "spellcheck_window");
  GLADE_HOOKUP_OBJECT (spellcheck_window, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (spellcheck_window, table2, "table2");
  GLADE_HOOKUP_OBJECT (spellcheck_window, misspelled_word_label, "misspelled_word_label");
  GLADE_HOOKUP_OBJECT (spellcheck_window, misspelled_word_entry, "misspelled_word_entry");
  GLADE_HOOKUP_OBJECT (spellcheck_window, replacement_label, "replacement_label");
  GLADE_HOOKUP_OBJECT (spellcheck_window, replacement_entry, "replacement_entry");
  GLADE_HOOKUP_OBJECT (spellcheck_window, suggestions_label, "suggestions_label");
  GLADE_HOOKUP_OBJECT (spellcheck_window, label50, "label50");
  GLADE_HOOKUP_OBJECT (spellcheck_window, spell_dict_combo, "spell_dict_combo");
  GLADE_HOOKUP_OBJECT (spellcheck_window, check_dict_combo_entry, "check_dict_combo_entry");
  GLADE_HOOKUP_OBJECT (spellcheck_window, vbox7, "vbox7");
  GLADE_HOOKUP_OBJECT (spellcheck_window, spell_orth_checkbutton, "spell_orth_checkbutton");
  GLADE_HOOKUP_OBJECT (spellcheck_window, spell_tr_checkbutton, "spell_tr_checkbutton");
  GLADE_HOOKUP_OBJECT (spellcheck_window, spell_eg_checkbutton, "spell_eg_checkbutton");
  GLADE_HOOKUP_OBJECT (spellcheck_window, spell_eg_tr_checkbutton, "spell_eg_tr_checkbutton");
  GLADE_HOOKUP_OBJECT (spellcheck_window, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (spellcheck_window, spell_headwords_radiobutton, "spell_headwords_radiobutton");
  GLADE_HOOKUP_OBJECT (spellcheck_window, spell_translations_radiobutton, "spell_translations_radiobutton");
  GLADE_HOOKUP_OBJECT (spellcheck_window, label49, "label49");
  GLADE_HOOKUP_OBJECT (spellcheck_window, scrolledwindow5, "scrolledwindow5");
  GLADE_HOOKUP_OBJECT (spellcheck_window, suggestions_treeview, "suggestions_treeview");
  GLADE_HOOKUP_OBJECT (spellcheck_window, spell_progressbar, "spell_progressbar");
  GLADE_HOOKUP_OBJECT (spellcheck_window, vbuttonbox1, "vbuttonbox1");
  GLADE_HOOKUP_OBJECT (spellcheck_window, spell_replace_button, "spell_replace_button");
  GLADE_HOOKUP_OBJECT (spellcheck_window, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (spellcheck_window, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (spellcheck_window, image9, "image9");
  GLADE_HOOKUP_OBJECT (spellcheck_window, label47, "label47");
  GLADE_HOOKUP_OBJECT (spellcheck_window, spell_replace_all_button, "spell_replace_all_button");
  GLADE_HOOKUP_OBJECT (spellcheck_window, spell_ignore_button, "spell_ignore_button");
  GLADE_HOOKUP_OBJECT (spellcheck_window, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (spellcheck_window, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (spellcheck_window, image10, "image10");
  GLADE_HOOKUP_OBJECT (spellcheck_window, label48, "label48");
  GLADE_HOOKUP_OBJECT (spellcheck_window, spell_ignore_all_button, "spell_ignore_all_button");
  GLADE_HOOKUP_OBJECT (spellcheck_window, spell_add_button, "spell_add_button");
  GLADE_HOOKUP_OBJECT (spellcheck_window, spell_close_button, "spell_close_button");
  GLADE_HOOKUP_OBJECT_NO_REF (spellcheck_window, tooltips, "tooltips");

  gtk_widget_grab_default (spell_replace_button);
  return spellcheck_window;
}

GtkWidget*
create_propertybox1 (void)
{
  GtkWidget *propertybox1;
  GtkWidget *preferences_notebook;
  GtkWidget *table3;
  GtkWidget *stylesheet_radiobutton1;
  GSList *stylesheet_radiobutton1_group = NULL;
  GtkWidget *stylesheet_radiobutton2;
  GtkWidget *default_stylesheetfn;
  GtkWidget *stylesheet_fileentry;
  GtkWidget *combo_entry1;
  GtkWidget *label54;
  GtkWidget *general_tab_label;
  GtkWidget *table4;
  GtkWidget *label56;
  GtkWidget *editer_entry;
  GtkWidget *editer_radiobutton1;
  GSList *editer_radiobutton1_group = NULL;
  GtkWidget *editer_radiobutton2;
  GtkWidget *editer_default_name_label;
  GtkWidget *scrolledwindow6;
  GtkWidget *entry_template_label;
  GtkWidget *template_radiobutton2;
  GSList *template_radiobutton2_group = NULL;
  GtkWidget *template_radiobutton1;
  GSList *template_radiobutton1_group = NULL;
  GtkWidget *entry_template_fileentry;
  GtkWidget *combo_entry3;
  GtkWidget *template_default_label;
  GtkWidget *checkbutton2;
  GtkWidget *radiobutton10;
  GtkWidget *radiobutton9;
  GtkWidget *editer_default_email__label;
  GtkWidget *entry5;
  GtkWidget *checkbutton3;
  GtkWidget *source_reference_entry;
  GtkWidget *combo_entry2;
  GtkWidget *types_treeview;
  GtkWidget *entry_editor_tab_label;
  GtkWidget *empty_notebook_page;
  GtkWidget *label60;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  propertybox1 = gnome_property_box_new ();
  gtk_window_set_title (GTK_WINDOW (propertybox1), _("FreeDict-Editor Preferences"));
  gtk_window_set_modal (GTK_WINDOW (propertybox1), TRUE);
  gtk_window_set_destroy_with_parent (GTK_WINDOW (propertybox1), TRUE);

  preferences_notebook = GNOME_PROPERTY_BOX (propertybox1)->notebook;
  gtk_widget_show (preferences_notebook);

  table3 = gtk_table_new (3, 3, FALSE);
  gtk_widget_show (table3);
  gtk_container_add (GTK_CONTAINER (preferences_notebook), table3);
  gtk_table_set_col_spacings (GTK_TABLE (table3), 4);

  stylesheet_radiobutton1 = gtk_radio_button_new_with_mnemonic (NULL, _("Use Default Value:"));
  gtk_widget_show (stylesheet_radiobutton1);
  gtk_table_attach (GTK_TABLE (table3), stylesheet_radiobutton1, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (stylesheet_radiobutton1), stylesheet_radiobutton1_group);
  stylesheet_radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (stylesheet_radiobutton1));

  stylesheet_radiobutton2 = gtk_radio_button_new_with_mnemonic (NULL, _("Use Custom Value"));
  gtk_widget_show (stylesheet_radiobutton2);
  gtk_table_attach (GTK_TABLE (table3), stylesheet_radiobutton2, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (stylesheet_radiobutton2), stylesheet_radiobutton1_group);
  stylesheet_radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (stylesheet_radiobutton2));

  default_stylesheetfn = gtk_label_new (_("label57"));
  gtk_widget_show (default_stylesheetfn);
  gtk_table_attach (GTK_TABLE (table3), default_stylesheetfn, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_SET_FLAGS (default_stylesheetfn, GTK_CAN_FOCUS);
  gtk_label_set_justify (GTK_LABEL (default_stylesheetfn), GTK_JUSTIFY_LEFT);
  gtk_label_set_selectable (GTK_LABEL (default_stylesheetfn), TRUE);
  gtk_misc_set_alignment (GTK_MISC (default_stylesheetfn), 0, 0.5);

  stylesheet_fileentry = gnome_file_entry_new (NULL, _("Select XSLT-Stylesheet"));
  gtk_widget_show (stylesheet_fileentry);
  gtk_table_attach (GTK_TABLE (table3), stylesheet_fileentry, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gnome_file_entry_set_modal (GNOME_FILE_ENTRY (stylesheet_fileentry), TRUE);

  combo_entry1 = gnome_file_entry_gtk_entry (GNOME_FILE_ENTRY (stylesheet_fileentry));
  gtk_widget_show (combo_entry1);

  label54 = gtk_label_new_with_mnemonic (_("_XSLT-Stylesheet for HTML Preview"));
  gtk_widget_show (label54);
  gtk_table_attach (GTK_TABLE (table3), label54, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label54), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label54), 0, 0.5);

  general_tab_label = gtk_label_new_with_mnemonic (_("_General"));
  gtk_widget_show (general_tab_label);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (preferences_notebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (preferences_notebook), 0), general_tab_label);
  gtk_label_set_justify (GTK_LABEL (general_tab_label), GTK_JUSTIFY_LEFT);

  table4 = gtk_table_new (8, 3, FALSE);
  gtk_widget_show (table4);
  gtk_container_add (GTK_CONTAINER (preferences_notebook), table4);

  label56 = gtk_label_new (_("POS-, Num-, Gen-, XRef-Types\n+\nDescriptions"));
  gtk_widget_show (label56);
  gtk_table_attach (GTK_TABLE (table4), label56, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  editer_entry = gtk_entry_new ();
  gtk_widget_show (editer_entry);
  gtk_table_attach (GTK_TABLE (table4), editer_entry, 2, 3, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, editer_entry, _("This information is automatically added to every edited entry"), NULL);

  editer_radiobutton1 = gtk_radio_button_new_with_mnemonic (NULL, _("Use Default Name:"));
  gtk_widget_show (editer_radiobutton1);
  gtk_table_attach (GTK_TABLE (table4), editer_radiobutton1, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (editer_radiobutton1), editer_radiobutton1_group);
  editer_radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (editer_radiobutton1));

  editer_radiobutton2 = gtk_radio_button_new_with_mnemonic (NULL, _("Use Custom Name:"));
  gtk_widget_show (editer_radiobutton2);
  gtk_table_attach (GTK_TABLE (table4), editer_radiobutton2, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (editer_radiobutton2), editer_radiobutton1_group);
  editer_radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (editer_radiobutton2));

  editer_default_name_label = gtk_label_new (_("editer_default_name_label"));
  gtk_widget_show (editer_default_name_label);
  gtk_table_attach (GTK_TABLE (table4), editer_default_name_label, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_SET_FLAGS (editer_default_name_label, GTK_CAN_FOCUS);
  gtk_label_set_justify (GTK_LABEL (editer_default_name_label), GTK_JUSTIFY_LEFT);
  gtk_label_set_selectable (GTK_LABEL (editer_default_name_label), TRUE);
  gtk_misc_set_alignment (GTK_MISC (editer_default_name_label), 0, 0.5);

  scrolledwindow6 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow6);
  gtk_table_attach (GTK_TABLE (table4), scrolledwindow6, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow6), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  entry_template_label = gtk_label_new_with_mnemonic (_("Entry _Template"));
  gtk_widget_show (entry_template_label);
  gtk_table_attach (GTK_TABLE (table4), entry_template_label, 0, 1, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (entry_template_label), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (entry_template_label), 0, 0.5);

  template_radiobutton2 = gtk_radio_button_new_with_mnemonic (NULL, _("Use Custom Value:"));
  gtk_widget_show (template_radiobutton2);
  gtk_table_attach (GTK_TABLE (table4), template_radiobutton2, 1, 2, 7, 8,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (template_radiobutton2), template_radiobutton2_group);
  template_radiobutton2_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (template_radiobutton2));

  template_radiobutton1 = gtk_radio_button_new_with_mnemonic (NULL, _("Use Default:"));
  gtk_widget_show (template_radiobutton1);
  gtk_table_attach (GTK_TABLE (table4), template_radiobutton1, 1, 2, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (template_radiobutton1), template_radiobutton1_group);
  template_radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (template_radiobutton1));

  entry_template_fileentry = gnome_file_entry_new (NULL, NULL);
  gtk_widget_show (entry_template_fileentry);
  gtk_table_attach (GTK_TABLE (table4), entry_template_fileentry, 2, 3, 7, 8,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  combo_entry3 = gnome_file_entry_gtk_entry (GNOME_FILE_ENTRY (entry_template_fileentry));
  gtk_widget_show (combo_entry3);

  template_default_label = gtk_label_new (_("template_default_label"));
  gtk_widget_show (template_default_label);
  gtk_table_attach (GTK_TABLE (table4), template_default_label, 2, 3, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_SET_FLAGS (template_default_label, GTK_CAN_FOCUS);
  gtk_label_set_justify (GTK_LABEL (template_default_label), GTK_JUSTIFY_LEFT);
  gtk_label_set_selectable (GTK_LABEL (template_default_label), TRUE);
  gtk_misc_set_alignment (GTK_MISC (template_default_label), 0, 0.5);

  checkbutton2 = gtk_check_button_new_with_mnemonic (_("Add _Author/Editor to Edited Entries"));
  gtk_widget_show (checkbutton2);
  gtk_table_attach (GTK_TABLE (table4), checkbutton2, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  radiobutton10 = gtk_radio_button_new_with_mnemonic (NULL, _("Use Custom Email:"));
  gtk_widget_show (radiobutton10);
  gtk_table_attach (GTK_TABLE (table4), radiobutton10, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton10), editer_radiobutton1_group);
  editer_radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton10));

  radiobutton9 = gtk_radio_button_new_with_mnemonic (NULL, _("Use Default Email:"));
  gtk_widget_show (radiobutton9);
  gtk_table_attach (GTK_TABLE (table4), radiobutton9, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton9), editer_radiobutton1_group);
  editer_radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton9));

  editer_default_email__label = gtk_label_new (_("editer_default_email_label"));
  gtk_widget_show (editer_default_email__label);
  gtk_table_attach (GTK_TABLE (table4), editer_default_email__label, 2, 3, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_SET_FLAGS (editer_default_email__label, GTK_CAN_FOCUS);
  gtk_label_set_justify (GTK_LABEL (editer_default_email__label), GTK_JUSTIFY_LEFT);
  gtk_label_set_selectable (GTK_LABEL (editer_default_email__label), TRUE);
  gtk_misc_set_alignment (GTK_MISC (editer_default_email__label), 0, 0.5);

  entry5 = gtk_entry_new ();
  gtk_widget_show (entry5);
  gtk_table_attach (GTK_TABLE (table4), entry5, 2, 3, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  checkbutton3 = gtk_check_button_new_with_mnemonic (_("Add _Source Reference to Edited Entries"));
  gtk_widget_show (checkbutton3);
  gtk_table_attach (GTK_TABLE (table4), checkbutton3, 0, 1, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  source_reference_entry = gnome_entry_new (NULL);
  gtk_widget_show (source_reference_entry);
  gtk_table_attach (GTK_TABLE (table4), source_reference_entry, 1, 3, 5, 6,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  combo_entry2 = gnome_entry_gtk_entry (GNOME_ENTRY (source_reference_entry));
  gtk_widget_show (combo_entry2);
  gtk_tooltips_set_tip (tooltips, combo_entry2, _("Source Document that justifies inclusion of an entry. Automatically added to edited entries."), NULL);

  types_treeview = gtk_tree_view_new ();
  gtk_widget_show (types_treeview);
  gtk_table_attach (GTK_TABLE (table4), types_treeview, 1, 3, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);
  gtk_tree_view_set_rules_hint (GTK_TREE_VIEW (types_treeview), TRUE);
  gtk_tree_view_set_reorderable (GTK_TREE_VIEW (types_treeview), TRUE);

  entry_editor_tab_label = gtk_label_new_with_mnemonic (_("_Entry Editor"));
  gtk_widget_show (entry_editor_tab_label);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (preferences_notebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (preferences_notebook), 1), entry_editor_tab_label);
  gtk_label_set_justify (GTK_LABEL (entry_editor_tab_label), GTK_JUSTIFY_LEFT);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (preferences_notebook), empty_notebook_page);

  label60 = gtk_label_new_with_mnemonic (_("_Sanity Checks"));
  gtk_widget_show (label60);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (preferences_notebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (preferences_notebook), 2), label60);
  gtk_label_set_justify (GTK_LABEL (label60), GTK_JUSTIFY_LEFT);

  g_signal_connect ((gpointer) propertybox1, "apply",
                    G_CALLBACK (on_propertybox1_apply),
                    NULL);
  g_signal_connect ((gpointer) propertybox1, "help",
                    G_CALLBACK (on_propertybox1_help),
                    NULL);
  g_signal_connect ((gpointer) propertybox1, "close",
                    G_CALLBACK (on_propertybox1_close),
                    NULL);
  g_signal_connect ((gpointer) stylesheet_fileentry, "changed",
                    G_CALLBACK (on_gtkeditable_changed),
                    NULL);
  g_signal_connect ((gpointer) editer_entry, "changed",
                    G_CALLBACK (on_gtkeditable_changed),
                    NULL);
  g_signal_connect ((gpointer) entry_template_fileentry, "changed",
                    G_CALLBACK (on_gtkeditable_changed),
                    NULL);
  g_signal_connect ((gpointer) source_reference_entry, "changed",
                    G_CALLBACK (on_gtkeditable_changed),
                    NULL);

  gtk_label_set_mnemonic_widget (GTK_LABEL (label54), combo_entry1);
  gtk_label_set_mnemonic_widget (GTK_LABEL (entry_template_label), combo_entry3);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (propertybox1, propertybox1, "propertybox1");
  GLADE_HOOKUP_OBJECT_NO_REF (propertybox1, preferences_notebook, "preferences_notebook");
  GLADE_HOOKUP_OBJECT (propertybox1, table3, "table3");
  GLADE_HOOKUP_OBJECT (propertybox1, stylesheet_radiobutton1, "stylesheet_radiobutton1");
  GLADE_HOOKUP_OBJECT (propertybox1, stylesheet_radiobutton2, "stylesheet_radiobutton2");
  GLADE_HOOKUP_OBJECT (propertybox1, default_stylesheetfn, "default_stylesheetfn");
  GLADE_HOOKUP_OBJECT (propertybox1, stylesheet_fileentry, "stylesheet_fileentry");
  GLADE_HOOKUP_OBJECT (propertybox1, combo_entry1, "combo_entry1");
  GLADE_HOOKUP_OBJECT (propertybox1, label54, "label54");
  GLADE_HOOKUP_OBJECT (propertybox1, general_tab_label, "general_tab_label");
  GLADE_HOOKUP_OBJECT (propertybox1, table4, "table4");
  GLADE_HOOKUP_OBJECT (propertybox1, label56, "label56");
  GLADE_HOOKUP_OBJECT (propertybox1, editer_entry, "editer_entry");
  GLADE_HOOKUP_OBJECT (propertybox1, editer_radiobutton1, "editer_radiobutton1");
  GLADE_HOOKUP_OBJECT (propertybox1, editer_radiobutton2, "editer_radiobutton2");
  GLADE_HOOKUP_OBJECT (propertybox1, editer_default_name_label, "editer_default_name_label");
  GLADE_HOOKUP_OBJECT (propertybox1, scrolledwindow6, "scrolledwindow6");
  GLADE_HOOKUP_OBJECT (propertybox1, entry_template_label, "entry_template_label");
  GLADE_HOOKUP_OBJECT (propertybox1, template_radiobutton2, "template_radiobutton2");
  GLADE_HOOKUP_OBJECT (propertybox1, template_radiobutton1, "template_radiobutton1");
  GLADE_HOOKUP_OBJECT (propertybox1, entry_template_fileentry, "entry_template_fileentry");
  GLADE_HOOKUP_OBJECT (propertybox1, combo_entry3, "combo_entry3");
  GLADE_HOOKUP_OBJECT (propertybox1, template_default_label, "template_default_label");
  GLADE_HOOKUP_OBJECT (propertybox1, checkbutton2, "checkbutton2");
  GLADE_HOOKUP_OBJECT (propertybox1, radiobutton10, "radiobutton10");
  GLADE_HOOKUP_OBJECT (propertybox1, radiobutton9, "radiobutton9");
  GLADE_HOOKUP_OBJECT (propertybox1, editer_default_email__label, "editer_default_email__label");
  GLADE_HOOKUP_OBJECT (propertybox1, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (propertybox1, checkbutton3, "checkbutton3");
  GLADE_HOOKUP_OBJECT (propertybox1, source_reference_entry, "source_reference_entry");
  GLADE_HOOKUP_OBJECT (propertybox1, combo_entry2, "combo_entry2");
  GLADE_HOOKUP_OBJECT (propertybox1, types_treeview, "types_treeview");
  GLADE_HOOKUP_OBJECT (propertybox1, entry_editor_tab_label, "entry_editor_tab_label");
  GLADE_HOOKUP_OBJECT (propertybox1, label60, "label60");
  GLADE_HOOKUP_OBJECT_NO_REF (propertybox1, tooltips, "tooltips");

  return propertybox1;
}

GtkWidget*
create_sanity_window (void)
{
  GtkWidget *sanity_window;
  GdkPixbuf *sanity_window_icon_pixbuf;
  GtkWidget *scrolledwindow7;
  GtkWidget *sanity_treeview;

  sanity_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (sanity_window, 100, 200);
  gtk_window_set_title (GTK_WINDOW (sanity_window), _("Check Sanity"));
  gtk_window_set_default_size (GTK_WINDOW (sanity_window), 200, 400);
  gtk_window_set_destroy_with_parent (GTK_WINDOW (sanity_window), TRUE);
  sanity_window_icon_pixbuf = create_pixbuf ("freedict-editor/freedict.png");
  if (sanity_window_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (sanity_window), sanity_window_icon_pixbuf);
      gdk_pixbuf_unref (sanity_window_icon_pixbuf);
    }

  scrolledwindow7 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow7);
  gtk_container_add (GTK_CONTAINER (sanity_window), scrolledwindow7);

  sanity_treeview = gtk_tree_view_new ();
  gtk_widget_show (sanity_treeview);
  gtk_container_add (GTK_CONTAINER (scrolledwindow7), sanity_treeview);
  gtk_widget_set_size_request (sanity_treeview, 130, 200);
  gtk_tree_view_set_rules_hint (GTK_TREE_VIEW (sanity_treeview), TRUE);
  gtk_tree_view_set_reorderable (GTK_TREE_VIEW (sanity_treeview), TRUE);

  g_signal_connect ((gpointer) sanity_window, "show",
                    G_CALLBACK (on_sanity_window_show),
                    NULL);
  g_signal_connect ((gpointer) sanity_treeview, "row_activated",
                    G_CALLBACK (on_sanity_treeview_row_activated),
                    NULL);
  g_signal_connect ((gpointer) sanity_treeview, "cursor_changed",
                    G_CALLBACK (on_sanity_treeview_cursor_changed),
                    NULL);
  g_signal_connect ((gpointer) sanity_treeview, "expand_collapse_cursor_row",
                    G_CALLBACK (on_sanity_treeview_expand_collapse_cursor_row),
                    NULL);
  g_signal_connect ((gpointer) sanity_treeview, "row_expanded",
                    G_CALLBACK (on_sanity_treeview_row_expanded),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (sanity_window, sanity_window, "sanity_window");
  GLADE_HOOKUP_OBJECT (sanity_window, scrolledwindow7, "scrolledwindow7");
  GLADE_HOOKUP_OBJECT (sanity_window, sanity_treeview, "sanity_treeview");

  return sanity_window;
}

