/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gnome.h>

#include "interface.h"
#include "support.h"

GtkWidget* app1;

int
main (int argc, char *argv[])
{

  poptContext con;
  GnomeProgram *app = gnome_program_init (PACKAGE, VERSION, LIBGNOMEUI_MODULE,
                      argc, argv,
                      GNOME_PARAM_APP_DATADIR, PACKAGE_DATA_DIR,
		      LIBGNOMEUI_PARAM_DEFAULT_ICON,
		        PACKAGE_DATA_DIR "/pixmaps/" PACKAGE "/freedict.png",
                      NULL);

  g_object_get(G_OBJECT(app), GNOME_PARAM_POPT_CONTEXT, &con, NULL);
  extern char *selected_filename;
  selected_filename = (char *) poptGetArg(con);
 
  poptFreeContext(con);
  
  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */

  extern void myload(const char *filename);
  app1 = create_app1();
  gtk_widget_show_all(app1);
  if(selected_filename) myload(selected_filename);
  
  gtk_main ();
  return 0;
}
