/*
 * This file was generated by orbit-idl-2 - DO NOT EDIT!
 */

#include <string.h>
#define ORBIT2_STUBS_API
#define ORBIT_IDL_C_COMMON
#define Spell_1_0_5_COMMON
#include "Spell-1.0.5.h"

static const CORBA_unsigned_long ORBit_zero_int = 0;

#if ( (TC_IMPL_TC_CORBA_sequence_CORBA_string_0 == 'S') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_1 == 'p') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_2 == 'e') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_3 == 'l') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_4 == 'l') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_5 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_6 == '1') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_7 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_8 == '0') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_9 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_10 == '5') \
) && !defined(TC_DEF_TC_CORBA_sequence_CORBA_string)
#define TC_DEF_TC_CORBA_sequence_CORBA_string 1
static const CORBA_TypeCode anon_subtypes_array1[] =
   { (CORBA_TypeCode) & TC_CORBA_string_struct };
#ifdef ORBIT_IDL_C_IMODULE_Spell_1_0_5
static
#endif
const struct CORBA_TypeCode_struct TC_CORBA_sequence_CORBA_string_struct = {
   {&ORBit_TypeCode_epv, ORBIT_REFCOUNT_STATIC},
   CORBA_tk_sequence,
   0,
   0,
   MAX(ORBIT_ALIGNOF_CORBA_POINTER,
       MAX(ORBIT_ALIGNOF_CORBA_LONG, MAX(ORBIT_ALIGNOF_CORBA_STRUCT, 1))),
   0,
   1,
   (CORBA_TypeCode *) anon_subtypes_array1,
   CORBA_OBJECT_NIL,
   NULL,
   NULL,
   NULL,
   NULL,
   -1,
   0,
   0, 0
};
#endif
#if ( (TC_IMPL_TC_CORBA_sequence_CORBA_string_0 == 'S') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_1 == 'p') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_2 == 'e') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_3 == 'l') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_4 == 'l') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_5 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_6 == '1') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_7 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_8 == '0') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_9 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_10 == '5') \
) && !defined(TC_DEF_TC_CORBA_sequence_CORBA_string)
#define TC_DEF_TC_CORBA_sequence_CORBA_string 1
static const CORBA_TypeCode anon_subtypes_array8[] =
   { (CORBA_TypeCode) & TC_CORBA_string_struct };
#ifdef ORBIT_IDL_C_IMODULE_Spell_1_0_5
static
#endif
const struct CORBA_TypeCode_struct TC_CORBA_sequence_CORBA_string_struct = {
   {&ORBit_TypeCode_epv, ORBIT_REFCOUNT_STATIC},
   CORBA_tk_sequence,
   0,
   0,
   MAX(ORBIT_ALIGNOF_CORBA_POINTER,
       MAX(ORBIT_ALIGNOF_CORBA_LONG, MAX(ORBIT_ALIGNOF_CORBA_STRUCT, 1))),
   0,
   1,
   (CORBA_TypeCode *) anon_subtypes_array8,
   CORBA_OBJECT_NIL,
   NULL,
   NULL,
   NULL,
   NULL,
   -1,
   0,
   0, 0
};
#endif
#if ( (TC_IMPL_TC_GNOME_Spell_StringSeq_0 == 'S') \
&& (TC_IMPL_TC_GNOME_Spell_StringSeq_1 == 'p') \
&& (TC_IMPL_TC_GNOME_Spell_StringSeq_2 == 'e') \
&& (TC_IMPL_TC_GNOME_Spell_StringSeq_3 == 'l') \
&& (TC_IMPL_TC_GNOME_Spell_StringSeq_4 == 'l') \
&& (TC_IMPL_TC_GNOME_Spell_StringSeq_5 == '_') \
&& (TC_IMPL_TC_GNOME_Spell_StringSeq_6 == '1') \
&& (TC_IMPL_TC_GNOME_Spell_StringSeq_7 == '_') \
&& (TC_IMPL_TC_GNOME_Spell_StringSeq_8 == '0') \
&& (TC_IMPL_TC_GNOME_Spell_StringSeq_9 == '_') \
&& (TC_IMPL_TC_GNOME_Spell_StringSeq_10 == '5') \
) && !defined(TC_DEF_TC_GNOME_Spell_StringSeq)
#define TC_DEF_TC_GNOME_Spell_StringSeq 1
static const CORBA_TypeCode anon_subtypes_array11[] =
   { (CORBA_TypeCode) & TC_CORBA_sequence_CORBA_string_struct };
#ifdef ORBIT_IDL_C_IMODULE_Spell_1_0_5
static
#endif
const struct CORBA_TypeCode_struct TC_GNOME_Spell_StringSeq_struct = {
   {&ORBit_TypeCode_epv, ORBIT_REFCOUNT_STATIC},
   CORBA_tk_alias,
   0,
   0,
   MAX(ORBIT_ALIGNOF_CORBA_POINTER,
       MAX(ORBIT_ALIGNOF_CORBA_LONG, MAX(ORBIT_ALIGNOF_CORBA_STRUCT, 1))),
   0,
   1,
   (CORBA_TypeCode *) anon_subtypes_array11,
   CORBA_OBJECT_NIL,
   "StringSeq",
   "IDL:GNOME/Spell/StringSeq:1.0",
   NULL,
   NULL,
   -1,
   0,
   0, 0
};
#endif
#if ( (TC_IMPL_TC_GNOME_Spell_Language_0 == 'S') \
&& (TC_IMPL_TC_GNOME_Spell_Language_1 == 'p') \
&& (TC_IMPL_TC_GNOME_Spell_Language_2 == 'e') \
&& (TC_IMPL_TC_GNOME_Spell_Language_3 == 'l') \
&& (TC_IMPL_TC_GNOME_Spell_Language_4 == 'l') \
&& (TC_IMPL_TC_GNOME_Spell_Language_5 == '_') \
&& (TC_IMPL_TC_GNOME_Spell_Language_6 == '1') \
&& (TC_IMPL_TC_GNOME_Spell_Language_7 == '_') \
&& (TC_IMPL_TC_GNOME_Spell_Language_8 == '0') \
&& (TC_IMPL_TC_GNOME_Spell_Language_9 == '_') \
&& (TC_IMPL_TC_GNOME_Spell_Language_10 == '5') \
) && !defined(TC_DEF_TC_GNOME_Spell_Language)
#define TC_DEF_TC_GNOME_Spell_Language 1
static const char *anon_subnames_array13[] = { "name", "abbreviation" };
static const CORBA_TypeCode anon_subtypes_array14[] =
   { (CORBA_TypeCode) & TC_CORBA_string_struct,
(CORBA_TypeCode) & TC_CORBA_string_struct };
#ifdef ORBIT_IDL_C_IMODULE_Spell_1_0_5
static
#endif
const struct CORBA_TypeCode_struct TC_GNOME_Spell_Language_struct = {
   {&ORBit_TypeCode_epv, ORBIT_REFCOUNT_STATIC},
   CORBA_tk_struct,
   0,
   0,
   ORBIT_ALIGNOF_CORBA_POINTER,
   0,
   2,
   (CORBA_TypeCode *) anon_subtypes_array14,
   CORBA_OBJECT_NIL,
   "Language",
   "IDL:GNOME/Spell/Language:1.0",
   (char **) anon_subnames_array13,
   NULL,
   -1,
   0,
   0, 0
};
#endif
#if ( (TC_IMPL_TC_CORBA_sequence_GNOME_Spell_Language_0 == 'S') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_Spell_Language_1 == 'p') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_Spell_Language_2 == 'e') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_Spell_Language_3 == 'l') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_Spell_Language_4 == 'l') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_Spell_Language_5 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_Spell_Language_6 == '1') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_Spell_Language_7 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_Spell_Language_8 == '0') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_Spell_Language_9 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_Spell_Language_10 == '5') \
) && !defined(TC_DEF_TC_CORBA_sequence_GNOME_Spell_Language)
#define TC_DEF_TC_CORBA_sequence_GNOME_Spell_Language 1
static const CORBA_TypeCode anon_subtypes_array17[] =
   { (CORBA_TypeCode) & TC_GNOME_Spell_Language_struct };
#ifdef ORBIT_IDL_C_IMODULE_Spell_1_0_5
static
#endif
const struct CORBA_TypeCode_struct
   TC_CORBA_sequence_GNOME_Spell_Language_struct = {
   {&ORBit_TypeCode_epv, ORBIT_REFCOUNT_STATIC},
   CORBA_tk_sequence,
   0,
   0,
   MAX(ORBIT_ALIGNOF_CORBA_POINTER,
       MAX(ORBIT_ALIGNOF_CORBA_LONG, MAX(ORBIT_ALIGNOF_CORBA_STRUCT, 1))),
   0,
   1,
   (CORBA_TypeCode *) anon_subtypes_array17,
   CORBA_OBJECT_NIL,
   NULL,
   NULL,
   NULL,
   NULL,
   -1,
   0,
   0, 0
};
#endif
#if ( (TC_IMPL_TC_CORBA_sequence_GNOME_Spell_Language_0 == 'S') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_Spell_Language_1 == 'p') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_Spell_Language_2 == 'e') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_Spell_Language_3 == 'l') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_Spell_Language_4 == 'l') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_Spell_Language_5 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_Spell_Language_6 == '1') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_Spell_Language_7 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_Spell_Language_8 == '0') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_Spell_Language_9 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_Spell_Language_10 == '5') \
) && !defined(TC_DEF_TC_CORBA_sequence_GNOME_Spell_Language)
#define TC_DEF_TC_CORBA_sequence_GNOME_Spell_Language 1
static const CORBA_TypeCode anon_subtypes_array24[] =
   { (CORBA_TypeCode) & TC_GNOME_Spell_Language_struct };
#ifdef ORBIT_IDL_C_IMODULE_Spell_1_0_5
static
#endif
const struct CORBA_TypeCode_struct
   TC_CORBA_sequence_GNOME_Spell_Language_struct = {
   {&ORBit_TypeCode_epv, ORBIT_REFCOUNT_STATIC},
   CORBA_tk_sequence,
   0,
   0,
   MAX(ORBIT_ALIGNOF_CORBA_POINTER,
       MAX(ORBIT_ALIGNOF_CORBA_LONG, MAX(ORBIT_ALIGNOF_CORBA_STRUCT, 1))),
   0,
   1,
   (CORBA_TypeCode *) anon_subtypes_array24,
   CORBA_OBJECT_NIL,
   NULL,
   NULL,
   NULL,
   NULL,
   -1,
   0,
   0, 0
};
#endif
#if ( (TC_IMPL_TC_GNOME_Spell_LanguageSeq_0 == 'S') \
&& (TC_IMPL_TC_GNOME_Spell_LanguageSeq_1 == 'p') \
&& (TC_IMPL_TC_GNOME_Spell_LanguageSeq_2 == 'e') \
&& (TC_IMPL_TC_GNOME_Spell_LanguageSeq_3 == 'l') \
&& (TC_IMPL_TC_GNOME_Spell_LanguageSeq_4 == 'l') \
&& (TC_IMPL_TC_GNOME_Spell_LanguageSeq_5 == '_') \
&& (TC_IMPL_TC_GNOME_Spell_LanguageSeq_6 == '1') \
&& (TC_IMPL_TC_GNOME_Spell_LanguageSeq_7 == '_') \
&& (TC_IMPL_TC_GNOME_Spell_LanguageSeq_8 == '0') \
&& (TC_IMPL_TC_GNOME_Spell_LanguageSeq_9 == '_') \
&& (TC_IMPL_TC_GNOME_Spell_LanguageSeq_10 == '5') \
) && !defined(TC_DEF_TC_GNOME_Spell_LanguageSeq)
#define TC_DEF_TC_GNOME_Spell_LanguageSeq 1
static const CORBA_TypeCode anon_subtypes_array27[] =
   { (CORBA_TypeCode) & TC_CORBA_sequence_GNOME_Spell_Language_struct };
#ifdef ORBIT_IDL_C_IMODULE_Spell_1_0_5
static
#endif
const struct CORBA_TypeCode_struct TC_GNOME_Spell_LanguageSeq_struct = {
   {&ORBit_TypeCode_epv, ORBIT_REFCOUNT_STATIC},
   CORBA_tk_alias,
   0,
   0,
   MAX(ORBIT_ALIGNOF_CORBA_POINTER,
       MAX(ORBIT_ALIGNOF_CORBA_LONG, MAX(ORBIT_ALIGNOF_CORBA_STRUCT, 1))),
   0,
   1,
   (CORBA_TypeCode *) anon_subtypes_array27,
   CORBA_OBJECT_NIL,
   "LanguageSeq",
   "IDL:GNOME/Spell/LanguageSeq:1.0",
   NULL,
   NULL,
   -1,
   0,
   0, 0
};
#endif
#if ( (TC_IMPL_TC_GNOME_Spell_Dictionary_Error_0 == 'S') \
&& (TC_IMPL_TC_GNOME_Spell_Dictionary_Error_1 == 'p') \
&& (TC_IMPL_TC_GNOME_Spell_Dictionary_Error_2 == 'e') \
&& (TC_IMPL_TC_GNOME_Spell_Dictionary_Error_3 == 'l') \
&& (TC_IMPL_TC_GNOME_Spell_Dictionary_Error_4 == 'l') \
&& (TC_IMPL_TC_GNOME_Spell_Dictionary_Error_5 == '_') \
&& (TC_IMPL_TC_GNOME_Spell_Dictionary_Error_6 == '1') \
&& (TC_IMPL_TC_GNOME_Spell_Dictionary_Error_7 == '_') \
&& (TC_IMPL_TC_GNOME_Spell_Dictionary_Error_8 == '0') \
&& (TC_IMPL_TC_GNOME_Spell_Dictionary_Error_9 == '_') \
&& (TC_IMPL_TC_GNOME_Spell_Dictionary_Error_10 == '5') \
) && !defined(TC_DEF_TC_GNOME_Spell_Dictionary_Error)
#define TC_DEF_TC_GNOME_Spell_Dictionary_Error 1
static const char *anon_subnames_array29[] = { "error" };
static const CORBA_TypeCode anon_subtypes_array30[] =
   { (CORBA_TypeCode) & TC_CORBA_string_struct };
#ifdef ORBIT_IDL_C_IMODULE_Spell_1_0_5
static
#endif
const struct CORBA_TypeCode_struct TC_GNOME_Spell_Dictionary_Error_struct = {
   {&ORBit_TypeCode_epv, ORBIT_REFCOUNT_STATIC},
   CORBA_tk_except,
   0,
   0,
   ORBIT_ALIGNOF_CORBA_POINTER,
   0,
   1,
   (CORBA_TypeCode *) anon_subtypes_array30,
   CORBA_OBJECT_NIL,
   "Error",
   "IDL:GNOME/Spell/Dictionary/Error:1.0",
   (char **) anon_subnames_array29,
   NULL,
   -1,
   0,
   0, 0
};
#endif
#if ( (TC_IMPL_TC_GNOME_Spell_Dictionary_0 == 'S') \
&& (TC_IMPL_TC_GNOME_Spell_Dictionary_1 == 'p') \
&& (TC_IMPL_TC_GNOME_Spell_Dictionary_2 == 'e') \
&& (TC_IMPL_TC_GNOME_Spell_Dictionary_3 == 'l') \
&& (TC_IMPL_TC_GNOME_Spell_Dictionary_4 == 'l') \
&& (TC_IMPL_TC_GNOME_Spell_Dictionary_5 == '_') \
&& (TC_IMPL_TC_GNOME_Spell_Dictionary_6 == '1') \
&& (TC_IMPL_TC_GNOME_Spell_Dictionary_7 == '_') \
&& (TC_IMPL_TC_GNOME_Spell_Dictionary_8 == '0') \
&& (TC_IMPL_TC_GNOME_Spell_Dictionary_9 == '_') \
&& (TC_IMPL_TC_GNOME_Spell_Dictionary_10 == '5') \
) && !defined(TC_DEF_TC_GNOME_Spell_Dictionary)
#define TC_DEF_TC_GNOME_Spell_Dictionary 1
#ifdef ORBIT_IDL_C_IMODULE_Spell_1_0_5
static
#endif
const struct CORBA_TypeCode_struct TC_GNOME_Spell_Dictionary_struct = {
   {&ORBit_TypeCode_epv, ORBIT_REFCOUNT_STATIC},
   CORBA_tk_objref,
   0,
   0,
   ORBIT_ALIGNOF_CORBA_POINTER,
   0,
   0,
   NULL,
   CORBA_OBJECT_NIL,
   "Dictionary",
   "IDL:GNOME/Spell/Dictionary:1.0",
   NULL,
   NULL,
   -1,
   0,
   0, 0
};
#endif

#ifndef ORBIT_IDL_C_IMODULE_Spell_1_0_5
CORBA_unsigned_long GNOME_Spell_Dictionary__classid = 0;
#endif

/* Interface type data */

static ORBit_IArg GNOME_Spell_Dictionary_setLanguage__arginfo[] = {
   {TC_CORBA_string, ORBit_I_ARG_IN, "language"}
};
static ORBit_IArg GNOME_Spell_Dictionary_checkWord__arginfo[] = {
   {TC_CORBA_string, ORBit_I_ARG_IN, "word"}
};

/* Exceptions */
static CORBA_TypeCode GNOME_Spell_Dictionary_checkWord__exceptinfo[] = {
   TC_GNOME_Spell_Dictionary_Error,
   NULL
};
static ORBit_IArg GNOME_Spell_Dictionary_getSuggestions__arginfo[] = {
   {TC_CORBA_string, ORBit_I_ARG_IN, "word"}
};

/* Exceptions */
static CORBA_TypeCode GNOME_Spell_Dictionary_getSuggestions__exceptinfo[] = {
   TC_GNOME_Spell_Dictionary_Error,
   NULL
};
static ORBit_IArg GNOME_Spell_Dictionary_addWordToSession__arginfo[] = {
   {TC_CORBA_string, ORBit_I_ARG_IN, "word"}
};

/* Exceptions */
static CORBA_TypeCode GNOME_Spell_Dictionary_addWordToSession__exceptinfo[] = {
   TC_GNOME_Spell_Dictionary_Error,
   NULL
};
static ORBit_IArg GNOME_Spell_Dictionary_addWordToPersonal__arginfo[] = {
   {TC_CORBA_string, ORBit_I_ARG_IN, "word"},
   {TC_CORBA_string, ORBit_I_ARG_IN, "language"}
};

/* Exceptions */
static CORBA_TypeCode GNOME_Spell_Dictionary_addWordToPersonal__exceptinfo[] = {
   TC_GNOME_Spell_Dictionary_Error,
   NULL
};
static ORBit_IArg GNOME_Spell_Dictionary_setCorrection__arginfo[] = {
   {TC_CORBA_string, ORBit_I_ARG_IN, "word"},
   {TC_CORBA_string, ORBit_I_ARG_IN, "replacement"},
   {TC_CORBA_string, ORBit_I_ARG_IN, "language"}
};

#ifdef ORBIT_IDL_C_IMODULE_Spell_1_0_5
static
#endif
ORBit_IMethod GNOME_Spell_Dictionary__imethods[] = {
   {
    {0, 0, NULL, FALSE},
    {0, 0, NULL, FALSE},
    {0, 0, NULL, FALSE},
    TC_GNOME_Spell_LanguageSeq, "getLanguages", 12,
    0}
   , {
      {1, 1, GNOME_Spell_Dictionary_setLanguage__arginfo, FALSE},
      {0, 0, NULL, FALSE},
      {0, 0, NULL, FALSE},
      TC_void, "setLanguage", 11,
      0}
   , {
      {1, 1, GNOME_Spell_Dictionary_checkWord__arginfo, FALSE},
      {0, 0, NULL, FALSE},
      {1, 1, GNOME_Spell_Dictionary_checkWord__exceptinfo, FALSE},
      TC_CORBA_boolean, "checkWord", 9,
      0 | ORBit_I_COMMON_FIXED_SIZE}
   , {
      {1, 1, GNOME_Spell_Dictionary_getSuggestions__arginfo, FALSE},
      {0, 0, NULL, FALSE},
      {1, 1, GNOME_Spell_Dictionary_getSuggestions__exceptinfo, FALSE},
      TC_GNOME_Spell_StringSeq, "getSuggestions", 14,
      0}
   , {
      {1, 1, GNOME_Spell_Dictionary_addWordToSession__arginfo, FALSE},
      {0, 0, NULL, FALSE},
      {1, 1, GNOME_Spell_Dictionary_addWordToSession__exceptinfo, FALSE},
      TC_void, "addWordToSession", 16,
      0}
   , {
      {2, 2, GNOME_Spell_Dictionary_addWordToPersonal__arginfo, FALSE},
      {0, 0, NULL, FALSE},
      {1, 1, GNOME_Spell_Dictionary_addWordToPersonal__exceptinfo, FALSE},
      TC_void, "addWordToPersonal", 17,
      0}
   , {
      {3, 3, GNOME_Spell_Dictionary_setCorrection__arginfo, FALSE},
      {0, 0, NULL, FALSE},
      {0, 0, NULL, FALSE},
      TC_void, "setCorrection", 13,
      0}
};
static CORBA_string GNOME_Spell_Dictionary__base_itypes[] = {
   "IDL:Bonobo/Unknown:1.0",
   "IDL:omg.org/CORBA/Object:1.0"
};

#ifdef ORBIT_IDL_C_IMODULE_Spell_1_0_5
static
#endif
ORBit_IInterface GNOME_Spell_Dictionary__iinterface = {
   TC_GNOME_Spell_Dictionary, {7, 7, GNOME_Spell_Dictionary__imethods, FALSE},
   {2, 2, GNOME_Spell_Dictionary__base_itypes, FALSE}
};
