FREEDICTDIR ?= ../../
DISTFILES = lit-eng.tei Makefile COPYING AUTHORS ChangeLog INSTALL \
         freedict-P5.dtd freedict-P5.rng freedict-P5.xml freedict-dictionary.css
include $(FREEDICTDIR)/tools/Makefile.common
