FREEDICTDIR ?= ../../
DISTFILES = AUTHORS ChangeLog COPYING slk-eng.tei INSTALL Makefile NEWS README \
    freedict-P5.dtd freedict-P5.rng freedict-P5.xml freedict-dictionary.css
include $(FREEDICTDIR)/tools/Makefile.common
