# The line below is really just a fallback and only works if you have got a copy of the tools directory at this location. It's better to set the environment variable in your shell.
FREEDICT_TOOLS ?= ../../tools
DISTFILES = AUTHORS COPYING ChangeLog INSTALL Makefile \
	README ukr-pol.tei freedict-P5.rng freedict-P5.xml \
	freedict-dictionary.css freedict-dictionary.xsl freedict-P5.dtd
include $(FREEDICT_TOOLS)/mk/dicts.mk
