FREEDICTDIR ?= ../../
DISTFILES = AUTHORS COPYING ChangeLog INSTALL Makefile \
	README ukr-pol.tei freedict-P5.rng freedict-P5.xml \
	freedict-dictionary.css freedict-dictionary.xsl freedict-P5.dtd
include $(FREEDICTDIR)/tools/Makefile.common
