FREEDICT_TOOLS ?= ..
DISTFILES = AUTHORS COPYING ChangeLog INSTALL Makefile \
	README slv-eng.tei freedict-P5.rng freedict-P5.xml \
	freedict-dictionary.css  freedict-dictionary.xsl freedict-P5.dtd

include $(FREEDICT_TOOLS)/mk/dicts.mk
