FREEDICTDIR ?= ..
DISTFILES = AUTHORS ChangeLog COPYING eng-iri.tei INSTALL Makefile NEWS README
# Clear this variable, because currently the .tei file already contains
# phonetics information.
supported_phonetics =
include $(FREEDICTDIR)/tools/Makefile.common
