FREEDICTDIR ?= ..
DISTFILES = kur-eng.txt Makefile kur-eng.tei kur-eng.tei.header README ChangeLog
include $(FREEDICTDIR)/tools/Makefile.common

#$(dictname).tei: $(dictname).txt $(dictname).tei.header \
#	$(FREEDICTDIR)/tools/xdf2tei.pl
#	cat $(dictname).tei.header >$@
#	$(FREEDICTDIR)/tools/xdf2tei.pl <$< >>$@
#	echo "</body></text></TEI.2>" >>$@

#clean::
#	-rm $(dictname).tei
