FREEDICTDIR ?= ../../
DISTFILES = ChangeLog COPYING eng-hun.tei \
	freedict-P5.xml freedict-P5.rng freedict-P5.dtd freedict-dictionary.css Makefile
supported_phonetics=
include $(FREEDICTDIR)/tools/Makefile.common

