# Choose!
# `sabcmd' comes with Sablotron, see gingerall.org
#XSLTPROCESSOR ?= sabcmd
# `xsltproc' comes with libxml/libxslt, see xmlsoft.org
# I prefer it here because of its less obtrusive <xsl:message> output.
# But on the other hand, the output doesn't include the line numbers
# where the message was generated. Also, xsltproc is a bit faster than sabcmd.
XSLTPROCESSOR ?= xsltproc -novalid

# set default value
FREEDICTDIR ?= ..

# where built files should get installed 
DESTDIR ?= /usr/share/dictd 
 
# the file xml.soc file comes with sp/opensp/openjade 
# and is required by nsgmls
XMLSOC ?= /usr/share/sgml/opensp/xml.soc

# you can also set this in ~/.bashrc
SGML_CATALOG_FILES ?= /var/lib/sgml/CATALOG.tei_4xml:/var/lib/sgml/CATALOG.iso_ent

TEI2DICTFLAGS += -u

# dictfmts pre 1.10 are considered "old" and don't understand the --utf8 switch
old_dictfmt := $(shell dictfmt --version | perl -pe '\
if(/^dictfmt v. (\d+)\.(\d+)(\.(\d+))?.*/)\
{ exit (($$1>=1 && $$2 >= 10 && ($$4 eq "" || $$4 >=1)) ? 0 : 1); };\
exit 2;'; echo $$?)

ifeq ($(old_dictfmt), 1)
DICTD_LOCALE ?= en_GB.utf8
DICTFMTFLAGS += --locale $(DICTD_LOCALE)
else
DICTFMTFLAGS += --utf8
endif

# this tool comes with libbedic, see http://www.sourceforge.net/projects/bedic
XEROX ?= xerox -d --verbose

charlint_in_path := $(shell which charlint.pl 2>/dev/null)
ifneq ($(charlint_in_path), )
CHARLINT := $(charlint_in_path)
else
CHARLINT := $(toolsdir)/charlint.pl
endif
CHARLINT_DATA := $(dir $(CHARLINT))charlint-unicodedata

# Command to start the Win32 Application
# that can convert '.vok. to '.tld'

ifneq ($(shell which wine 2 &> /dev/null),)
EVOLUTIONARY_MAKEDICT ?= wine C:\\Program\ Files\\Dictionary\\Dictionary.exe
else
ifeq ($(shell if [ -x /cygdrive/c/Programme/Dictionary/Dictionary.exe ]; then echo OK; fi),OK)
EVOLUTIONARY_MAKEDICT ?= /cygdrive/c/Programme/Dictionary/Dictionary.exe
endif
endif

