FREEDICTDIR ?= ..
DISTFILES = AUTHORS ChangeLog COPYING lat-deu.tei.header \
	    lat-deu.tei freedict-P5.dtd freedict-dictionary.css INSTALL Makefile NEWS README
include $(FREEDICTDIR)/tools/Makefile.common
#include $(toolsdir)/ergane/Makefile.inc

#$(dictname).tei: $(dictname).tei.header

# for teidiff: checkout an old revision
#old/$(dictname).tei:
#	cvs -z3 checkout -d old -D 2006-01-01 $(dictname)/$(dictname).tei

#not sure how to make it work for SVN, so I'm just commenting this out

#old = old/$(dictname).tei

