FREEDICTDIR ?= ../../
DISTFILES = AUTHORS ChangeLog COPYING lat-deu.tei \
freedict-P5.xml freedict-P5.rng freedict-P5.dtd freedict-dictionary.css INSTALL Makefile NEWS README
include $(FREEDICTDIR)/tools/Makefile.common

